<?php
/**
 * UserApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NoScope API
 *
 * Publicly available API for the NoScope platform. Requires authentication for all endpoints. Get your API key from the NoScope dashboard. API Rate Limiting applies to all endpoints and are currently capped at 100 requests per hour. Request api access at <a href='https://CSSkill.com/api'>https://CSSkill.com/api</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@CSSkill.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * UserApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'call40d2bb5b656516284d4a0b26e0886019' => [
            'application/json',
        ],
        'call664d8a8b84751129b40eea6e9c8fbefb' => [
            'application/json',
        ],
        'd34163056174558da0a65c7735a3b5e0' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation call40d2bb5b656516284d4a0b26e0886019
     *
     * Get a user by their steam_id
     *
     * @param   $UNKNOWN_PARAMETER_NAME The steam_id of the user (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['call40d2bb5b656516284d4a0b26e0886019'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\UserResponse
     */
    public function call40d2bb5b656516284d4a0b26e0886019($UNKNOWN_PARAMETER_NAME, string $contentType = self::contentTypes['call40d2bb5b656516284d4a0b26e0886019'][0])
    {
        list($response) = $this->call40d2bb5b656516284d4a0b26e0886019WithHttpInfo($UNKNOWN_PARAMETER_NAME, $contentType);
        return $response;
    }

    /**
     * Operation call40d2bb5b656516284d4a0b26e0886019WithHttpInfo
     *
     * Get a user by their steam_id
     *
     * @param   $UNKNOWN_PARAMETER_NAME The steam_id of the user (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['call40d2bb5b656516284d4a0b26e0886019'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\UserResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function call40d2bb5b656516284d4a0b26e0886019WithHttpInfo($UNKNOWN_PARAMETER_NAME, string $contentType = self::contentTypes['call40d2bb5b656516284d4a0b26e0886019'][0])
    {
        $request = $this->call40d2bb5b656516284d4a0b26e0886019Request($UNKNOWN_PARAMETER_NAME, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\UserResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\UserResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\UserResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation call40d2bb5b656516284d4a0b26e0886019Async
     *
     * Get a user by their steam_id
     *
     * @param   $UNKNOWN_PARAMETER_NAME The steam_id of the user (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['call40d2bb5b656516284d4a0b26e0886019'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function call40d2bb5b656516284d4a0b26e0886019Async($UNKNOWN_PARAMETER_NAME, string $contentType = self::contentTypes['call40d2bb5b656516284d4a0b26e0886019'][0])
    {
        return $this->call40d2bb5b656516284d4a0b26e0886019AsyncWithHttpInfo($UNKNOWN_PARAMETER_NAME, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation call40d2bb5b656516284d4a0b26e0886019AsyncWithHttpInfo
     *
     * Get a user by their steam_id
     *
     * @param   $UNKNOWN_PARAMETER_NAME The steam_id of the user (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['call40d2bb5b656516284d4a0b26e0886019'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function call40d2bb5b656516284d4a0b26e0886019AsyncWithHttpInfo($UNKNOWN_PARAMETER_NAME, string $contentType = self::contentTypes['call40d2bb5b656516284d4a0b26e0886019'][0])
    {
        $returnType = '\OpenAPI\Client\Model\UserResponse';
        $request = $this->call40d2bb5b656516284d4a0b26e0886019Request($UNKNOWN_PARAMETER_NAME, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'call40d2bb5b656516284d4a0b26e0886019'
     *
     * @param   $UNKNOWN_PARAMETER_NAME The steam_id of the user (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['call40d2bb5b656516284d4a0b26e0886019'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function call40d2bb5b656516284d4a0b26e0886019Request($UNKNOWN_PARAMETER_NAME, string $contentType = self::contentTypes['call40d2bb5b656516284d4a0b26e0886019'][0])
    {

        // verify the required parameter 'UNKNOWN_PARAMETER_NAME' is set
        if ($UNKNOWN_PARAMETER_NAME === null || (is_array($UNKNOWN_PARAMETER_NAME) && count($UNKNOWN_PARAMETER_NAME) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $UNKNOWN_PARAMETER_NAME when calling call40d2bb5b656516284d4a0b26e0886019'
            );
        }


        $resourcePath = '/api/public/user/steam/{steam_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($UNKNOWN_PARAMETER_NAME !== null) {
            $resourcePath = str_replace(
                '{' . 'steam_id' . '}',
                ObjectSerializer::toPathValue($UNKNOWN_PARAMETER_NAME),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation call664d8a8b84751129b40eea6e9c8fbefb
     *
     * Get a user by their id
     *
     * @param   $UNKNOWN_PARAMETER_NAME The id of the user (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['call664d8a8b84751129b40eea6e9c8fbefb'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\UserResponse
     */
    public function call664d8a8b84751129b40eea6e9c8fbefb($UNKNOWN_PARAMETER_NAME, string $contentType = self::contentTypes['call664d8a8b84751129b40eea6e9c8fbefb'][0])
    {
        list($response) = $this->call664d8a8b84751129b40eea6e9c8fbefbWithHttpInfo($UNKNOWN_PARAMETER_NAME, $contentType);
        return $response;
    }

    /**
     * Operation call664d8a8b84751129b40eea6e9c8fbefbWithHttpInfo
     *
     * Get a user by their id
     *
     * @param   $UNKNOWN_PARAMETER_NAME The id of the user (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['call664d8a8b84751129b40eea6e9c8fbefb'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\UserResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function call664d8a8b84751129b40eea6e9c8fbefbWithHttpInfo($UNKNOWN_PARAMETER_NAME, string $contentType = self::contentTypes['call664d8a8b84751129b40eea6e9c8fbefb'][0])
    {
        $request = $this->call664d8a8b84751129b40eea6e9c8fbefbRequest($UNKNOWN_PARAMETER_NAME, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\UserResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\UserResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\UserResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation call664d8a8b84751129b40eea6e9c8fbefbAsync
     *
     * Get a user by their id
     *
     * @param   $UNKNOWN_PARAMETER_NAME The id of the user (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['call664d8a8b84751129b40eea6e9c8fbefb'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function call664d8a8b84751129b40eea6e9c8fbefbAsync($UNKNOWN_PARAMETER_NAME, string $contentType = self::contentTypes['call664d8a8b84751129b40eea6e9c8fbefb'][0])
    {
        return $this->call664d8a8b84751129b40eea6e9c8fbefbAsyncWithHttpInfo($UNKNOWN_PARAMETER_NAME, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation call664d8a8b84751129b40eea6e9c8fbefbAsyncWithHttpInfo
     *
     * Get a user by their id
     *
     * @param   $UNKNOWN_PARAMETER_NAME The id of the user (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['call664d8a8b84751129b40eea6e9c8fbefb'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function call664d8a8b84751129b40eea6e9c8fbefbAsyncWithHttpInfo($UNKNOWN_PARAMETER_NAME, string $contentType = self::contentTypes['call664d8a8b84751129b40eea6e9c8fbefb'][0])
    {
        $returnType = '\OpenAPI\Client\Model\UserResponse';
        $request = $this->call664d8a8b84751129b40eea6e9c8fbefbRequest($UNKNOWN_PARAMETER_NAME, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'call664d8a8b84751129b40eea6e9c8fbefb'
     *
     * @param   $UNKNOWN_PARAMETER_NAME The id of the user (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['call664d8a8b84751129b40eea6e9c8fbefb'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function call664d8a8b84751129b40eea6e9c8fbefbRequest($UNKNOWN_PARAMETER_NAME, string $contentType = self::contentTypes['call664d8a8b84751129b40eea6e9c8fbefb'][0])
    {

        // verify the required parameter 'UNKNOWN_PARAMETER_NAME' is set
        if ($UNKNOWN_PARAMETER_NAME === null || (is_array($UNKNOWN_PARAMETER_NAME) && count($UNKNOWN_PARAMETER_NAME) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $UNKNOWN_PARAMETER_NAME when calling call664d8a8b84751129b40eea6e9c8fbefb'
            );
        }


        $resourcePath = '/api/public/user/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($UNKNOWN_PARAMETER_NAME !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($UNKNOWN_PARAMETER_NAME),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation d34163056174558da0a65c7735a3b5e0
     *
     * Get recent matches for a user
     *
     * @param   $UNKNOWN_PARAMETER_NAME The id of the user (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['d34163056174558da0a65c7735a3b5e0'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\UserMatchesResponse
     */
    public function d34163056174558da0a65c7735a3b5e0($UNKNOWN_PARAMETER_NAME, string $contentType = self::contentTypes['d34163056174558da0a65c7735a3b5e0'][0])
    {
        list($response) = $this->d34163056174558da0a65c7735a3b5e0WithHttpInfo($UNKNOWN_PARAMETER_NAME, $contentType);
        return $response;
    }

    /**
     * Operation d34163056174558da0a65c7735a3b5e0WithHttpInfo
     *
     * Get recent matches for a user
     *
     * @param   $UNKNOWN_PARAMETER_NAME The id of the user (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['d34163056174558da0a65c7735a3b5e0'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\UserMatchesResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function d34163056174558da0a65c7735a3b5e0WithHttpInfo($UNKNOWN_PARAMETER_NAME, string $contentType = self::contentTypes['d34163056174558da0a65c7735a3b5e0'][0])
    {
        $request = $this->d34163056174558da0a65c7735a3b5e0Request($UNKNOWN_PARAMETER_NAME, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\UserMatchesResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\UserMatchesResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\UserMatchesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation d34163056174558da0a65c7735a3b5e0Async
     *
     * Get recent matches for a user
     *
     * @param   $UNKNOWN_PARAMETER_NAME The id of the user (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['d34163056174558da0a65c7735a3b5e0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function d34163056174558da0a65c7735a3b5e0Async($UNKNOWN_PARAMETER_NAME, string $contentType = self::contentTypes['d34163056174558da0a65c7735a3b5e0'][0])
    {
        return $this->d34163056174558da0a65c7735a3b5e0AsyncWithHttpInfo($UNKNOWN_PARAMETER_NAME, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation d34163056174558da0a65c7735a3b5e0AsyncWithHttpInfo
     *
     * Get recent matches for a user
     *
     * @param   $UNKNOWN_PARAMETER_NAME The id of the user (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['d34163056174558da0a65c7735a3b5e0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function d34163056174558da0a65c7735a3b5e0AsyncWithHttpInfo($UNKNOWN_PARAMETER_NAME, string $contentType = self::contentTypes['d34163056174558da0a65c7735a3b5e0'][0])
    {
        $returnType = '\OpenAPI\Client\Model\UserMatchesResponse';
        $request = $this->d34163056174558da0a65c7735a3b5e0Request($UNKNOWN_PARAMETER_NAME, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'd34163056174558da0a65c7735a3b5e0'
     *
     * @param   $UNKNOWN_PARAMETER_NAME The id of the user (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['d34163056174558da0a65c7735a3b5e0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function d34163056174558da0a65c7735a3b5e0Request($UNKNOWN_PARAMETER_NAME, string $contentType = self::contentTypes['d34163056174558da0a65c7735a3b5e0'][0])
    {

        // verify the required parameter 'UNKNOWN_PARAMETER_NAME' is set
        if ($UNKNOWN_PARAMETER_NAME === null || (is_array($UNKNOWN_PARAMETER_NAME) && count($UNKNOWN_PARAMETER_NAME) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $UNKNOWN_PARAMETER_NAME when calling d34163056174558da0a65c7735a3b5e0'
            );
        }


        $resourcePath = '/api/public/user/{id}/matches';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($UNKNOWN_PARAMETER_NAME !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($UNKNOWN_PARAMETER_NAME),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
