<?php
/**
 * MatchUserStatsResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NoScope API
 *
 * Publicly available API for the NoScope platform. Requires authentication for all endpoints. Get your API key from the NoScope dashboard. API Rate Limiting applies to all endpoints and are currently capped at 100 requests per hour. Request api access at <a href='https://CSSkill.com/api'>https://CSSkill.com/api</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@CSSkill.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * MatchUserStatsResponse Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MatchUserStatsResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MatchUserStatsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'steam_id' => 'string',
        'user_id' => 'string',
        'player_name' => 'string',
        'team' => 'string',
        'kills' => 'int',
        'deaths' => 'int',
        'assists' => 'int',
        'headshot_kills' => 'int',
        'headshot_percentage' => 'float',
        'mvps' => 'int',
        'score' => 'int',
        'total_damage' => 'int',
        'utility_damage' => 'int',
        'he_damage' => 'int',
        'molotov_damage' => 'int',
        'weapon_damage' => 'int',
        'damage_per_shot' => 'float',
        'average_damage_per_round' => 'float',
        'opening_kills' => 'int',
        'opening_deaths' => 'int',
        'first_kills' => 'int',
        'first_deaths' => 'int',
        'rounds_2k' => 'int',
        'rounds_3k' => 'int',
        'rounds_4k' => 'int',
        'rounds_5k' => 'int',
        'rounds_ace' => 'int',
        'clutch_1v1_attempts' => 'int',
        'clutch_1v1_won' => 'int',
        'clutch_1v1_saved' => 'int',
        'clutch_1v2_attempts' => 'int',
        'clutch_1v2_won' => 'int',
        'clutch_1v2_saved' => 'int',
        'clutch_1v3_attempts' => 'int',
        'clutch_1v3_won' => 'int',
        'clutch_1v3_saved' => 'int',
        'clutch_1v4_attempts' => 'int',
        'clutch_1v4_won' => 'int',
        'clutch_1v4_saved' => 'int',
        'clutch_1v5_attempts' => 'int',
        'clutch_1v5_won' => 'int',
        'clutch_1v5_saved' => 'int',
        'average_equipment_value' => 'float',
        'total_cash_spent' => 'int',
        'flashbangs_thrown' => 'int',
        'smokes_thrown' => 'int',
        'he_grenades_thrown' => 'int',
        'molotovs_thrown' => 'int',
        'enemies_flashed' => 'int',
        'shots_fired' => 'int',
        'shots_hit' => 'int',
        'accuracy_percentage' => 'float',
        'kd_ratio' => 'float',
        'adr' => 'float',
        'kast_percentage' => 'float',
        'impact_rating' => 'float',
        'hltv_rating' => 'float',
        'hltv_rating_3' => 'float',
        'rating' => 'float',
        'personal_performance' => 'float',
        'spotted_accuracy' => 'float',
        'time_to_damage_ms' => 'int',
        'cross_placement_angle' => 'float',
        'head_accuracy_pct' => 'float',
        'spray_accuracy_pct' => 'float',
        'counter_strafe_quality' => 'float',
        'pistol_rounds' => 'int',
        'eco_rounds' => 'int',
        'semi_eco_rounds' => 'int',
        'force_buy_rounds' => 'int',
        'full_buy_rounds' => 'int',
        'trade_opportunities' => 'int',
        'trade_attempts' => 'int',
        'trade_kills' => 'int',
        'trades' => 'int',
        'was_traded' => 'int',
        'trade_kill_opportunities' => 'int',
        'trade_kill_attempts' => 'int',
        'trade_kill_success' => 'int',
        'trade_death_opportunities' => 'int',
        'trade_death_attempts' => 'int',
        'trade_death_success' => 'int',
        'teammates_flashed' => 'int',
        'flash_assists' => 'int',
        'avg_blind_time' => 'float',
        'enemies_blind_time' => 'float',
        'avg_he_damage' => 'float',
        'unused_utility_value' => 'int',
        'opening_duel_attempt_rate' => 'float',
        'opening_duel_success_rate' => 'float',
        'aim_score' => 'float',
        'utility_score' => 'float',
        'positioning_score' => 'float',
        'rounds_as_t' => 'int',
        'rounds_as_ct' => 'int',
        'kills_as_t' => 'int',
        'kills_as_ct' => 'int',
        'deaths_as_t' => 'int',
        'deaths_as_ct' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'steam_id' => 'uuid',
        'user_id' => 'uuid',
        'player_name' => null,
        'team' => null,
        'kills' => null,
        'deaths' => null,
        'assists' => null,
        'headshot_kills' => null,
        'headshot_percentage' => 'float',
        'mvps' => null,
        'score' => null,
        'total_damage' => null,
        'utility_damage' => null,
        'he_damage' => null,
        'molotov_damage' => null,
        'weapon_damage' => null,
        'damage_per_shot' => 'float',
        'average_damage_per_round' => 'float',
        'opening_kills' => null,
        'opening_deaths' => null,
        'first_kills' => null,
        'first_deaths' => null,
        'rounds_2k' => null,
        'rounds_3k' => null,
        'rounds_4k' => null,
        'rounds_5k' => null,
        'rounds_ace' => null,
        'clutch_1v1_attempts' => null,
        'clutch_1v1_won' => null,
        'clutch_1v1_saved' => null,
        'clutch_1v2_attempts' => null,
        'clutch_1v2_won' => null,
        'clutch_1v2_saved' => null,
        'clutch_1v3_attempts' => null,
        'clutch_1v3_won' => null,
        'clutch_1v3_saved' => null,
        'clutch_1v4_attempts' => null,
        'clutch_1v4_won' => null,
        'clutch_1v4_saved' => null,
        'clutch_1v5_attempts' => null,
        'clutch_1v5_won' => null,
        'clutch_1v5_saved' => null,
        'average_equipment_value' => 'float',
        'total_cash_spent' => null,
        'flashbangs_thrown' => null,
        'smokes_thrown' => null,
        'he_grenades_thrown' => null,
        'molotovs_thrown' => null,
        'enemies_flashed' => null,
        'shots_fired' => null,
        'shots_hit' => null,
        'accuracy_percentage' => 'float',
        'kd_ratio' => 'float',
        'adr' => 'float',
        'kast_percentage' => 'float',
        'impact_rating' => 'float',
        'hltv_rating' => 'float',
        'hltv_rating_3' => 'float',
        'rating' => 'float',
        'personal_performance' => 'float',
        'spotted_accuracy' => 'float',
        'time_to_damage_ms' => null,
        'cross_placement_angle' => 'float',
        'head_accuracy_pct' => 'float',
        'spray_accuracy_pct' => 'float',
        'counter_strafe_quality' => 'float',
        'pistol_rounds' => null,
        'eco_rounds' => null,
        'semi_eco_rounds' => null,
        'force_buy_rounds' => null,
        'full_buy_rounds' => null,
        'trade_opportunities' => null,
        'trade_attempts' => null,
        'trade_kills' => null,
        'trades' => null,
        'was_traded' => null,
        'trade_kill_opportunities' => null,
        'trade_kill_attempts' => null,
        'trade_kill_success' => null,
        'trade_death_opportunities' => null,
        'trade_death_attempts' => null,
        'trade_death_success' => null,
        'teammates_flashed' => null,
        'flash_assists' => null,
        'avg_blind_time' => 'float',
        'enemies_blind_time' => 'float',
        'avg_he_damage' => 'float',
        'unused_utility_value' => null,
        'opening_duel_attempt_rate' => 'float',
        'opening_duel_success_rate' => 'float',
        'aim_score' => 'float',
        'utility_score' => 'float',
        'positioning_score' => 'float',
        'rounds_as_t' => null,
        'rounds_as_ct' => null,
        'kills_as_t' => null,
        'kills_as_ct' => null,
        'deaths_as_t' => null,
        'deaths_as_ct' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'steam_id' => false,
        'user_id' => false,
        'player_name' => false,
        'team' => false,
        'kills' => false,
        'deaths' => false,
        'assists' => false,
        'headshot_kills' => false,
        'headshot_percentage' => false,
        'mvps' => false,
        'score' => false,
        'total_damage' => false,
        'utility_damage' => false,
        'he_damage' => false,
        'molotov_damage' => false,
        'weapon_damage' => false,
        'damage_per_shot' => false,
        'average_damage_per_round' => false,
        'opening_kills' => false,
        'opening_deaths' => false,
        'first_kills' => false,
        'first_deaths' => false,
        'rounds_2k' => false,
        'rounds_3k' => false,
        'rounds_4k' => false,
        'rounds_5k' => false,
        'rounds_ace' => false,
        'clutch_1v1_attempts' => false,
        'clutch_1v1_won' => false,
        'clutch_1v1_saved' => false,
        'clutch_1v2_attempts' => false,
        'clutch_1v2_won' => false,
        'clutch_1v2_saved' => false,
        'clutch_1v3_attempts' => false,
        'clutch_1v3_won' => false,
        'clutch_1v3_saved' => false,
        'clutch_1v4_attempts' => false,
        'clutch_1v4_won' => false,
        'clutch_1v4_saved' => false,
        'clutch_1v5_attempts' => false,
        'clutch_1v5_won' => false,
        'clutch_1v5_saved' => false,
        'average_equipment_value' => false,
        'total_cash_spent' => false,
        'flashbangs_thrown' => false,
        'smokes_thrown' => false,
        'he_grenades_thrown' => false,
        'molotovs_thrown' => false,
        'enemies_flashed' => false,
        'shots_fired' => false,
        'shots_hit' => false,
        'accuracy_percentage' => false,
        'kd_ratio' => false,
        'adr' => false,
        'kast_percentage' => false,
        'impact_rating' => false,
        'hltv_rating' => false,
        'hltv_rating_3' => false,
        'rating' => false,
        'personal_performance' => false,
        'spotted_accuracy' => false,
        'time_to_damage_ms' => false,
        'cross_placement_angle' => false,
        'head_accuracy_pct' => false,
        'spray_accuracy_pct' => false,
        'counter_strafe_quality' => false,
        'pistol_rounds' => false,
        'eco_rounds' => false,
        'semi_eco_rounds' => false,
        'force_buy_rounds' => false,
        'full_buy_rounds' => false,
        'trade_opportunities' => false,
        'trade_attempts' => false,
        'trade_kills' => false,
        'trades' => false,
        'was_traded' => false,
        'trade_kill_opportunities' => false,
        'trade_kill_attempts' => false,
        'trade_kill_success' => false,
        'trade_death_opportunities' => false,
        'trade_death_attempts' => false,
        'trade_death_success' => false,
        'teammates_flashed' => false,
        'flash_assists' => false,
        'avg_blind_time' => false,
        'enemies_blind_time' => false,
        'avg_he_damage' => false,
        'unused_utility_value' => false,
        'opening_duel_attempt_rate' => false,
        'opening_duel_success_rate' => false,
        'aim_score' => false,
        'utility_score' => false,
        'positioning_score' => false,
        'rounds_as_t' => false,
        'rounds_as_ct' => false,
        'kills_as_t' => false,
        'kills_as_ct' => false,
        'deaths_as_t' => false,
        'deaths_as_ct' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'steam_id' => 'steam_id',
        'user_id' => 'user_id',
        'player_name' => 'player_name',
        'team' => 'team',
        'kills' => 'kills',
        'deaths' => 'deaths',
        'assists' => 'assists',
        'headshot_kills' => 'headshot_kills',
        'headshot_percentage' => 'headshot_percentage',
        'mvps' => 'mvps',
        'score' => 'score',
        'total_damage' => 'total_damage',
        'utility_damage' => 'utility_damage',
        'he_damage' => 'he_damage',
        'molotov_damage' => 'molotov_damage',
        'weapon_damage' => 'weapon_damage',
        'damage_per_shot' => 'damage_per_shot',
        'average_damage_per_round' => 'average_damage_per_round',
        'opening_kills' => 'opening_kills',
        'opening_deaths' => 'opening_deaths',
        'first_kills' => 'first_kills',
        'first_deaths' => 'first_deaths',
        'rounds_2k' => 'rounds_2k',
        'rounds_3k' => 'rounds_3k',
        'rounds_4k' => 'rounds_4k',
        'rounds_5k' => 'rounds_5k',
        'rounds_ace' => 'rounds_ace',
        'clutch_1v1_attempts' => 'clutch_1v1_attempts',
        'clutch_1v1_won' => 'clutch_1v1_won',
        'clutch_1v1_saved' => 'clutch_1v1_saved',
        'clutch_1v2_attempts' => 'clutch_1v2_attempts',
        'clutch_1v2_won' => 'clutch_1v2_won',
        'clutch_1v2_saved' => 'clutch_1v2_saved',
        'clutch_1v3_attempts' => 'clutch_1v3_attempts',
        'clutch_1v3_won' => 'clutch_1v3_won',
        'clutch_1v3_saved' => 'clutch_1v3_saved',
        'clutch_1v4_attempts' => 'clutch_1v4_attempts',
        'clutch_1v4_won' => 'clutch_1v4_won',
        'clutch_1v4_saved' => 'clutch_1v4_saved',
        'clutch_1v5_attempts' => 'clutch_1v5_attempts',
        'clutch_1v5_won' => 'clutch_1v5_won',
        'clutch_1v5_saved' => 'clutch_1v5_saved',
        'average_equipment_value' => 'average_equipment_value',
        'total_cash_spent' => 'total_cash_spent',
        'flashbangs_thrown' => 'flashbangs_thrown',
        'smokes_thrown' => 'smokes_thrown',
        'he_grenades_thrown' => 'he_grenades_thrown',
        'molotovs_thrown' => 'molotovs_thrown',
        'enemies_flashed' => 'enemies_flashed',
        'shots_fired' => 'shots_fired',
        'shots_hit' => 'shots_hit',
        'accuracy_percentage' => 'accuracy_percentage',
        'kd_ratio' => 'kd_ratio',
        'adr' => 'adr',
        'kast_percentage' => 'kast_percentage',
        'impact_rating' => 'impact_rating',
        'hltv_rating' => 'hltv_rating',
        'hltv_rating_3' => 'hltv_rating_3',
        'rating' => 'rating',
        'personal_performance' => 'personal_performance',
        'spotted_accuracy' => 'spotted_accuracy',
        'time_to_damage_ms' => 'time_to_damage_ms',
        'cross_placement_angle' => 'cross_placement_angle',
        'head_accuracy_pct' => 'head_accuracy_pct',
        'spray_accuracy_pct' => 'spray_accuracy_pct',
        'counter_strafe_quality' => 'counter_strafe_quality',
        'pistol_rounds' => 'pistol_rounds',
        'eco_rounds' => 'eco_rounds',
        'semi_eco_rounds' => 'semi_eco_rounds',
        'force_buy_rounds' => 'force_buy_rounds',
        'full_buy_rounds' => 'full_buy_rounds',
        'trade_opportunities' => 'trade_opportunities',
        'trade_attempts' => 'trade_attempts',
        'trade_kills' => 'trade_kills',
        'trades' => 'trades',
        'was_traded' => 'was_traded',
        'trade_kill_opportunities' => 'trade_kill_opportunities',
        'trade_kill_attempts' => 'trade_kill_attempts',
        'trade_kill_success' => 'trade_kill_success',
        'trade_death_opportunities' => 'trade_death_opportunities',
        'trade_death_attempts' => 'trade_death_attempts',
        'trade_death_success' => 'trade_death_success',
        'teammates_flashed' => 'teammates_flashed',
        'flash_assists' => 'flash_assists',
        'avg_blind_time' => 'avg_blind_time',
        'enemies_blind_time' => 'enemies_blind_time',
        'avg_he_damage' => 'avg_he_damage',
        'unused_utility_value' => 'unused_utility_value',
        'opening_duel_attempt_rate' => 'opening_duel_attempt_rate',
        'opening_duel_success_rate' => 'opening_duel_success_rate',
        'aim_score' => 'aim_score',
        'utility_score' => 'utility_score',
        'positioning_score' => 'positioning_score',
        'rounds_as_t' => 'rounds_as_t',
        'rounds_as_ct' => 'rounds_as_ct',
        'kills_as_t' => 'kills_as_t',
        'kills_as_ct' => 'kills_as_ct',
        'deaths_as_t' => 'deaths_as_t',
        'deaths_as_ct' => 'deaths_as_ct'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'steam_id' => 'setSteamId',
        'user_id' => 'setUserId',
        'player_name' => 'setPlayerName',
        'team' => 'setTeam',
        'kills' => 'setKills',
        'deaths' => 'setDeaths',
        'assists' => 'setAssists',
        'headshot_kills' => 'setHeadshotKills',
        'headshot_percentage' => 'setHeadshotPercentage',
        'mvps' => 'setMvps',
        'score' => 'setScore',
        'total_damage' => 'setTotalDamage',
        'utility_damage' => 'setUtilityDamage',
        'he_damage' => 'setHeDamage',
        'molotov_damage' => 'setMolotovDamage',
        'weapon_damage' => 'setWeaponDamage',
        'damage_per_shot' => 'setDamagePerShot',
        'average_damage_per_round' => 'setAverageDamagePerRound',
        'opening_kills' => 'setOpeningKills',
        'opening_deaths' => 'setOpeningDeaths',
        'first_kills' => 'setFirstKills',
        'first_deaths' => 'setFirstDeaths',
        'rounds_2k' => 'setRounds2k',
        'rounds_3k' => 'setRounds3k',
        'rounds_4k' => 'setRounds4k',
        'rounds_5k' => 'setRounds5k',
        'rounds_ace' => 'setRoundsAce',
        'clutch_1v1_attempts' => 'setClutch1v1Attempts',
        'clutch_1v1_won' => 'setClutch1v1Won',
        'clutch_1v1_saved' => 'setClutch1v1Saved',
        'clutch_1v2_attempts' => 'setClutch1v2Attempts',
        'clutch_1v2_won' => 'setClutch1v2Won',
        'clutch_1v2_saved' => 'setClutch1v2Saved',
        'clutch_1v3_attempts' => 'setClutch1v3Attempts',
        'clutch_1v3_won' => 'setClutch1v3Won',
        'clutch_1v3_saved' => 'setClutch1v3Saved',
        'clutch_1v4_attempts' => 'setClutch1v4Attempts',
        'clutch_1v4_won' => 'setClutch1v4Won',
        'clutch_1v4_saved' => 'setClutch1v4Saved',
        'clutch_1v5_attempts' => 'setClutch1v5Attempts',
        'clutch_1v5_won' => 'setClutch1v5Won',
        'clutch_1v5_saved' => 'setClutch1v5Saved',
        'average_equipment_value' => 'setAverageEquipmentValue',
        'total_cash_spent' => 'setTotalCashSpent',
        'flashbangs_thrown' => 'setFlashbangsThrown',
        'smokes_thrown' => 'setSmokesThrown',
        'he_grenades_thrown' => 'setHeGrenadesThrown',
        'molotovs_thrown' => 'setMolotovsThrown',
        'enemies_flashed' => 'setEnemiesFlashed',
        'shots_fired' => 'setShotsFired',
        'shots_hit' => 'setShotsHit',
        'accuracy_percentage' => 'setAccuracyPercentage',
        'kd_ratio' => 'setKdRatio',
        'adr' => 'setAdr',
        'kast_percentage' => 'setKastPercentage',
        'impact_rating' => 'setImpactRating',
        'hltv_rating' => 'setHltvRating',
        'hltv_rating_3' => 'setHltvRating3',
        'rating' => 'setRating',
        'personal_performance' => 'setPersonalPerformance',
        'spotted_accuracy' => 'setSpottedAccuracy',
        'time_to_damage_ms' => 'setTimeToDamageMs',
        'cross_placement_angle' => 'setCrossPlacementAngle',
        'head_accuracy_pct' => 'setHeadAccuracyPct',
        'spray_accuracy_pct' => 'setSprayAccuracyPct',
        'counter_strafe_quality' => 'setCounterStrafeQuality',
        'pistol_rounds' => 'setPistolRounds',
        'eco_rounds' => 'setEcoRounds',
        'semi_eco_rounds' => 'setSemiEcoRounds',
        'force_buy_rounds' => 'setForceBuyRounds',
        'full_buy_rounds' => 'setFullBuyRounds',
        'trade_opportunities' => 'setTradeOpportunities',
        'trade_attempts' => 'setTradeAttempts',
        'trade_kills' => 'setTradeKills',
        'trades' => 'setTrades',
        'was_traded' => 'setWasTraded',
        'trade_kill_opportunities' => 'setTradeKillOpportunities',
        'trade_kill_attempts' => 'setTradeKillAttempts',
        'trade_kill_success' => 'setTradeKillSuccess',
        'trade_death_opportunities' => 'setTradeDeathOpportunities',
        'trade_death_attempts' => 'setTradeDeathAttempts',
        'trade_death_success' => 'setTradeDeathSuccess',
        'teammates_flashed' => 'setTeammatesFlashed',
        'flash_assists' => 'setFlashAssists',
        'avg_blind_time' => 'setAvgBlindTime',
        'enemies_blind_time' => 'setEnemiesBlindTime',
        'avg_he_damage' => 'setAvgHeDamage',
        'unused_utility_value' => 'setUnusedUtilityValue',
        'opening_duel_attempt_rate' => 'setOpeningDuelAttemptRate',
        'opening_duel_success_rate' => 'setOpeningDuelSuccessRate',
        'aim_score' => 'setAimScore',
        'utility_score' => 'setUtilityScore',
        'positioning_score' => 'setPositioningScore',
        'rounds_as_t' => 'setRoundsAsT',
        'rounds_as_ct' => 'setRoundsAsCt',
        'kills_as_t' => 'setKillsAsT',
        'kills_as_ct' => 'setKillsAsCt',
        'deaths_as_t' => 'setDeathsAsT',
        'deaths_as_ct' => 'setDeathsAsCt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'steam_id' => 'getSteamId',
        'user_id' => 'getUserId',
        'player_name' => 'getPlayerName',
        'team' => 'getTeam',
        'kills' => 'getKills',
        'deaths' => 'getDeaths',
        'assists' => 'getAssists',
        'headshot_kills' => 'getHeadshotKills',
        'headshot_percentage' => 'getHeadshotPercentage',
        'mvps' => 'getMvps',
        'score' => 'getScore',
        'total_damage' => 'getTotalDamage',
        'utility_damage' => 'getUtilityDamage',
        'he_damage' => 'getHeDamage',
        'molotov_damage' => 'getMolotovDamage',
        'weapon_damage' => 'getWeaponDamage',
        'damage_per_shot' => 'getDamagePerShot',
        'average_damage_per_round' => 'getAverageDamagePerRound',
        'opening_kills' => 'getOpeningKills',
        'opening_deaths' => 'getOpeningDeaths',
        'first_kills' => 'getFirstKills',
        'first_deaths' => 'getFirstDeaths',
        'rounds_2k' => 'getRounds2k',
        'rounds_3k' => 'getRounds3k',
        'rounds_4k' => 'getRounds4k',
        'rounds_5k' => 'getRounds5k',
        'rounds_ace' => 'getRoundsAce',
        'clutch_1v1_attempts' => 'getClutch1v1Attempts',
        'clutch_1v1_won' => 'getClutch1v1Won',
        'clutch_1v1_saved' => 'getClutch1v1Saved',
        'clutch_1v2_attempts' => 'getClutch1v2Attempts',
        'clutch_1v2_won' => 'getClutch1v2Won',
        'clutch_1v2_saved' => 'getClutch1v2Saved',
        'clutch_1v3_attempts' => 'getClutch1v3Attempts',
        'clutch_1v3_won' => 'getClutch1v3Won',
        'clutch_1v3_saved' => 'getClutch1v3Saved',
        'clutch_1v4_attempts' => 'getClutch1v4Attempts',
        'clutch_1v4_won' => 'getClutch1v4Won',
        'clutch_1v4_saved' => 'getClutch1v4Saved',
        'clutch_1v5_attempts' => 'getClutch1v5Attempts',
        'clutch_1v5_won' => 'getClutch1v5Won',
        'clutch_1v5_saved' => 'getClutch1v5Saved',
        'average_equipment_value' => 'getAverageEquipmentValue',
        'total_cash_spent' => 'getTotalCashSpent',
        'flashbangs_thrown' => 'getFlashbangsThrown',
        'smokes_thrown' => 'getSmokesThrown',
        'he_grenades_thrown' => 'getHeGrenadesThrown',
        'molotovs_thrown' => 'getMolotovsThrown',
        'enemies_flashed' => 'getEnemiesFlashed',
        'shots_fired' => 'getShotsFired',
        'shots_hit' => 'getShotsHit',
        'accuracy_percentage' => 'getAccuracyPercentage',
        'kd_ratio' => 'getKdRatio',
        'adr' => 'getAdr',
        'kast_percentage' => 'getKastPercentage',
        'impact_rating' => 'getImpactRating',
        'hltv_rating' => 'getHltvRating',
        'hltv_rating_3' => 'getHltvRating3',
        'rating' => 'getRating',
        'personal_performance' => 'getPersonalPerformance',
        'spotted_accuracy' => 'getSpottedAccuracy',
        'time_to_damage_ms' => 'getTimeToDamageMs',
        'cross_placement_angle' => 'getCrossPlacementAngle',
        'head_accuracy_pct' => 'getHeadAccuracyPct',
        'spray_accuracy_pct' => 'getSprayAccuracyPct',
        'counter_strafe_quality' => 'getCounterStrafeQuality',
        'pistol_rounds' => 'getPistolRounds',
        'eco_rounds' => 'getEcoRounds',
        'semi_eco_rounds' => 'getSemiEcoRounds',
        'force_buy_rounds' => 'getForceBuyRounds',
        'full_buy_rounds' => 'getFullBuyRounds',
        'trade_opportunities' => 'getTradeOpportunities',
        'trade_attempts' => 'getTradeAttempts',
        'trade_kills' => 'getTradeKills',
        'trades' => 'getTrades',
        'was_traded' => 'getWasTraded',
        'trade_kill_opportunities' => 'getTradeKillOpportunities',
        'trade_kill_attempts' => 'getTradeKillAttempts',
        'trade_kill_success' => 'getTradeKillSuccess',
        'trade_death_opportunities' => 'getTradeDeathOpportunities',
        'trade_death_attempts' => 'getTradeDeathAttempts',
        'trade_death_success' => 'getTradeDeathSuccess',
        'teammates_flashed' => 'getTeammatesFlashed',
        'flash_assists' => 'getFlashAssists',
        'avg_blind_time' => 'getAvgBlindTime',
        'enemies_blind_time' => 'getEnemiesBlindTime',
        'avg_he_damage' => 'getAvgHeDamage',
        'unused_utility_value' => 'getUnusedUtilityValue',
        'opening_duel_attempt_rate' => 'getOpeningDuelAttemptRate',
        'opening_duel_success_rate' => 'getOpeningDuelSuccessRate',
        'aim_score' => 'getAimScore',
        'utility_score' => 'getUtilityScore',
        'positioning_score' => 'getPositioningScore',
        'rounds_as_t' => 'getRoundsAsT',
        'rounds_as_ct' => 'getRoundsAsCt',
        'kills_as_t' => 'getKillsAsT',
        'kills_as_ct' => 'getKillsAsCt',
        'deaths_as_t' => 'getDeathsAsT',
        'deaths_as_ct' => 'getDeathsAsCt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('steam_id', $data ?? [], null);
        $this->setIfExists('user_id', $data ?? [], null);
        $this->setIfExists('player_name', $data ?? [], null);
        $this->setIfExists('team', $data ?? [], null);
        $this->setIfExists('kills', $data ?? [], null);
        $this->setIfExists('deaths', $data ?? [], null);
        $this->setIfExists('assists', $data ?? [], null);
        $this->setIfExists('headshot_kills', $data ?? [], null);
        $this->setIfExists('headshot_percentage', $data ?? [], null);
        $this->setIfExists('mvps', $data ?? [], null);
        $this->setIfExists('score', $data ?? [], null);
        $this->setIfExists('total_damage', $data ?? [], null);
        $this->setIfExists('utility_damage', $data ?? [], null);
        $this->setIfExists('he_damage', $data ?? [], null);
        $this->setIfExists('molotov_damage', $data ?? [], null);
        $this->setIfExists('weapon_damage', $data ?? [], null);
        $this->setIfExists('damage_per_shot', $data ?? [], null);
        $this->setIfExists('average_damage_per_round', $data ?? [], null);
        $this->setIfExists('opening_kills', $data ?? [], null);
        $this->setIfExists('opening_deaths', $data ?? [], null);
        $this->setIfExists('first_kills', $data ?? [], null);
        $this->setIfExists('first_deaths', $data ?? [], null);
        $this->setIfExists('rounds_2k', $data ?? [], null);
        $this->setIfExists('rounds_3k', $data ?? [], null);
        $this->setIfExists('rounds_4k', $data ?? [], null);
        $this->setIfExists('rounds_5k', $data ?? [], null);
        $this->setIfExists('rounds_ace', $data ?? [], null);
        $this->setIfExists('clutch_1v1_attempts', $data ?? [], null);
        $this->setIfExists('clutch_1v1_won', $data ?? [], null);
        $this->setIfExists('clutch_1v1_saved', $data ?? [], null);
        $this->setIfExists('clutch_1v2_attempts', $data ?? [], null);
        $this->setIfExists('clutch_1v2_won', $data ?? [], null);
        $this->setIfExists('clutch_1v2_saved', $data ?? [], null);
        $this->setIfExists('clutch_1v3_attempts', $data ?? [], null);
        $this->setIfExists('clutch_1v3_won', $data ?? [], null);
        $this->setIfExists('clutch_1v3_saved', $data ?? [], null);
        $this->setIfExists('clutch_1v4_attempts', $data ?? [], null);
        $this->setIfExists('clutch_1v4_won', $data ?? [], null);
        $this->setIfExists('clutch_1v4_saved', $data ?? [], null);
        $this->setIfExists('clutch_1v5_attempts', $data ?? [], null);
        $this->setIfExists('clutch_1v5_won', $data ?? [], null);
        $this->setIfExists('clutch_1v5_saved', $data ?? [], null);
        $this->setIfExists('average_equipment_value', $data ?? [], null);
        $this->setIfExists('total_cash_spent', $data ?? [], null);
        $this->setIfExists('flashbangs_thrown', $data ?? [], null);
        $this->setIfExists('smokes_thrown', $data ?? [], null);
        $this->setIfExists('he_grenades_thrown', $data ?? [], null);
        $this->setIfExists('molotovs_thrown', $data ?? [], null);
        $this->setIfExists('enemies_flashed', $data ?? [], null);
        $this->setIfExists('shots_fired', $data ?? [], null);
        $this->setIfExists('shots_hit', $data ?? [], null);
        $this->setIfExists('accuracy_percentage', $data ?? [], null);
        $this->setIfExists('kd_ratio', $data ?? [], null);
        $this->setIfExists('adr', $data ?? [], null);
        $this->setIfExists('kast_percentage', $data ?? [], null);
        $this->setIfExists('impact_rating', $data ?? [], null);
        $this->setIfExists('hltv_rating', $data ?? [], null);
        $this->setIfExists('hltv_rating_3', $data ?? [], null);
        $this->setIfExists('rating', $data ?? [], null);
        $this->setIfExists('personal_performance', $data ?? [], null);
        $this->setIfExists('spotted_accuracy', $data ?? [], null);
        $this->setIfExists('time_to_damage_ms', $data ?? [], null);
        $this->setIfExists('cross_placement_angle', $data ?? [], null);
        $this->setIfExists('head_accuracy_pct', $data ?? [], null);
        $this->setIfExists('spray_accuracy_pct', $data ?? [], null);
        $this->setIfExists('counter_strafe_quality', $data ?? [], null);
        $this->setIfExists('pistol_rounds', $data ?? [], null);
        $this->setIfExists('eco_rounds', $data ?? [], null);
        $this->setIfExists('semi_eco_rounds', $data ?? [], null);
        $this->setIfExists('force_buy_rounds', $data ?? [], null);
        $this->setIfExists('full_buy_rounds', $data ?? [], null);
        $this->setIfExists('trade_opportunities', $data ?? [], null);
        $this->setIfExists('trade_attempts', $data ?? [], null);
        $this->setIfExists('trade_kills', $data ?? [], null);
        $this->setIfExists('trades', $data ?? [], null);
        $this->setIfExists('was_traded', $data ?? [], null);
        $this->setIfExists('trade_kill_opportunities', $data ?? [], null);
        $this->setIfExists('trade_kill_attempts', $data ?? [], null);
        $this->setIfExists('trade_kill_success', $data ?? [], null);
        $this->setIfExists('trade_death_opportunities', $data ?? [], null);
        $this->setIfExists('trade_death_attempts', $data ?? [], null);
        $this->setIfExists('trade_death_success', $data ?? [], null);
        $this->setIfExists('teammates_flashed', $data ?? [], null);
        $this->setIfExists('flash_assists', $data ?? [], null);
        $this->setIfExists('avg_blind_time', $data ?? [], null);
        $this->setIfExists('enemies_blind_time', $data ?? [], null);
        $this->setIfExists('avg_he_damage', $data ?? [], null);
        $this->setIfExists('unused_utility_value', $data ?? [], null);
        $this->setIfExists('opening_duel_attempt_rate', $data ?? [], null);
        $this->setIfExists('opening_duel_success_rate', $data ?? [], null);
        $this->setIfExists('aim_score', $data ?? [], null);
        $this->setIfExists('utility_score', $data ?? [], null);
        $this->setIfExists('positioning_score', $data ?? [], null);
        $this->setIfExists('rounds_as_t', $data ?? [], null);
        $this->setIfExists('rounds_as_ct', $data ?? [], null);
        $this->setIfExists('kills_as_t', $data ?? [], null);
        $this->setIfExists('kills_as_ct', $data ?? [], null);
        $this->setIfExists('deaths_as_t', $data ?? [], null);
        $this->setIfExists('deaths_as_ct', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets steam_id
     *
     * @return string|null
     */
    public function getSteamId()
    {
        return $this->container['steam_id'];
    }

    /**
     * Sets steam_id
     *
     * @param string|null $steam_id steam_id
     *
     * @return self
     */
    public function setSteamId($steam_id)
    {
        if (is_null($steam_id)) {
            throw new \InvalidArgumentException('non-nullable steam_id cannot be null');
        }
        $this->container['steam_id'] = $steam_id;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return string|null
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string|null $user_id user_id
     *
     * @return self
     */
    public function setUserId($user_id)
    {
        if (is_null($user_id)) {
            throw new \InvalidArgumentException('non-nullable user_id cannot be null');
        }
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets player_name
     *
     * @return string|null
     */
    public function getPlayerName()
    {
        return $this->container['player_name'];
    }

    /**
     * Sets player_name
     *
     * @param string|null $player_name player_name
     *
     * @return self
     */
    public function setPlayerName($player_name)
    {
        if (is_null($player_name)) {
            throw new \InvalidArgumentException('non-nullable player_name cannot be null');
        }
        $this->container['player_name'] = $player_name;

        return $this;
    }

    /**
     * Gets team
     *
     * @return string|null
     */
    public function getTeam()
    {
        return $this->container['team'];
    }

    /**
     * Sets team
     *
     * @param string|null $team team
     *
     * @return self
     */
    public function setTeam($team)
    {
        if (is_null($team)) {
            throw new \InvalidArgumentException('non-nullable team cannot be null');
        }
        $this->container['team'] = $team;

        return $this;
    }

    /**
     * Gets kills
     *
     * @return int|null
     */
    public function getKills()
    {
        return $this->container['kills'];
    }

    /**
     * Sets kills
     *
     * @param int|null $kills kills
     *
     * @return self
     */
    public function setKills($kills)
    {
        if (is_null($kills)) {
            throw new \InvalidArgumentException('non-nullable kills cannot be null');
        }
        $this->container['kills'] = $kills;

        return $this;
    }

    /**
     * Gets deaths
     *
     * @return int|null
     */
    public function getDeaths()
    {
        return $this->container['deaths'];
    }

    /**
     * Sets deaths
     *
     * @param int|null $deaths deaths
     *
     * @return self
     */
    public function setDeaths($deaths)
    {
        if (is_null($deaths)) {
            throw new \InvalidArgumentException('non-nullable deaths cannot be null');
        }
        $this->container['deaths'] = $deaths;

        return $this;
    }

    /**
     * Gets assists
     *
     * @return int|null
     */
    public function getAssists()
    {
        return $this->container['assists'];
    }

    /**
     * Sets assists
     *
     * @param int|null $assists assists
     *
     * @return self
     */
    public function setAssists($assists)
    {
        if (is_null($assists)) {
            throw new \InvalidArgumentException('non-nullable assists cannot be null');
        }
        $this->container['assists'] = $assists;

        return $this;
    }

    /**
     * Gets headshot_kills
     *
     * @return int|null
     */
    public function getHeadshotKills()
    {
        return $this->container['headshot_kills'];
    }

    /**
     * Sets headshot_kills
     *
     * @param int|null $headshot_kills headshot_kills
     *
     * @return self
     */
    public function setHeadshotKills($headshot_kills)
    {
        if (is_null($headshot_kills)) {
            throw new \InvalidArgumentException('non-nullable headshot_kills cannot be null');
        }
        $this->container['headshot_kills'] = $headshot_kills;

        return $this;
    }

    /**
     * Gets headshot_percentage
     *
     * @return float|null
     */
    public function getHeadshotPercentage()
    {
        return $this->container['headshot_percentage'];
    }

    /**
     * Sets headshot_percentage
     *
     * @param float|null $headshot_percentage headshot_percentage
     *
     * @return self
     */
    public function setHeadshotPercentage($headshot_percentage)
    {
        if (is_null($headshot_percentage)) {
            throw new \InvalidArgumentException('non-nullable headshot_percentage cannot be null');
        }
        $this->container['headshot_percentage'] = $headshot_percentage;

        return $this;
    }

    /**
     * Gets mvps
     *
     * @return int|null
     */
    public function getMvps()
    {
        return $this->container['mvps'];
    }

    /**
     * Sets mvps
     *
     * @param int|null $mvps mvps
     *
     * @return self
     */
    public function setMvps($mvps)
    {
        if (is_null($mvps)) {
            throw new \InvalidArgumentException('non-nullable mvps cannot be null');
        }
        $this->container['mvps'] = $mvps;

        return $this;
    }

    /**
     * Gets score
     *
     * @return int|null
     */
    public function getScore()
    {
        return $this->container['score'];
    }

    /**
     * Sets score
     *
     * @param int|null $score score
     *
     * @return self
     */
    public function setScore($score)
    {
        if (is_null($score)) {
            throw new \InvalidArgumentException('non-nullable score cannot be null');
        }
        $this->container['score'] = $score;

        return $this;
    }

    /**
     * Gets total_damage
     *
     * @return int|null
     */
    public function getTotalDamage()
    {
        return $this->container['total_damage'];
    }

    /**
     * Sets total_damage
     *
     * @param int|null $total_damage total_damage
     *
     * @return self
     */
    public function setTotalDamage($total_damage)
    {
        if (is_null($total_damage)) {
            throw new \InvalidArgumentException('non-nullable total_damage cannot be null');
        }
        $this->container['total_damage'] = $total_damage;

        return $this;
    }

    /**
     * Gets utility_damage
     *
     * @return int|null
     */
    public function getUtilityDamage()
    {
        return $this->container['utility_damage'];
    }

    /**
     * Sets utility_damage
     *
     * @param int|null $utility_damage utility_damage
     *
     * @return self
     */
    public function setUtilityDamage($utility_damage)
    {
        if (is_null($utility_damage)) {
            throw new \InvalidArgumentException('non-nullable utility_damage cannot be null');
        }
        $this->container['utility_damage'] = $utility_damage;

        return $this;
    }

    /**
     * Gets he_damage
     *
     * @return int|null
     */
    public function getHeDamage()
    {
        return $this->container['he_damage'];
    }

    /**
     * Sets he_damage
     *
     * @param int|null $he_damage he_damage
     *
     * @return self
     */
    public function setHeDamage($he_damage)
    {
        if (is_null($he_damage)) {
            throw new \InvalidArgumentException('non-nullable he_damage cannot be null');
        }
        $this->container['he_damage'] = $he_damage;

        return $this;
    }

    /**
     * Gets molotov_damage
     *
     * @return int|null
     */
    public function getMolotovDamage()
    {
        return $this->container['molotov_damage'];
    }

    /**
     * Sets molotov_damage
     *
     * @param int|null $molotov_damage molotov_damage
     *
     * @return self
     */
    public function setMolotovDamage($molotov_damage)
    {
        if (is_null($molotov_damage)) {
            throw new \InvalidArgumentException('non-nullable molotov_damage cannot be null');
        }
        $this->container['molotov_damage'] = $molotov_damage;

        return $this;
    }

    /**
     * Gets weapon_damage
     *
     * @return int|null
     */
    public function getWeaponDamage()
    {
        return $this->container['weapon_damage'];
    }

    /**
     * Sets weapon_damage
     *
     * @param int|null $weapon_damage weapon_damage
     *
     * @return self
     */
    public function setWeaponDamage($weapon_damage)
    {
        if (is_null($weapon_damage)) {
            throw new \InvalidArgumentException('non-nullable weapon_damage cannot be null');
        }
        $this->container['weapon_damage'] = $weapon_damage;

        return $this;
    }

    /**
     * Gets damage_per_shot
     *
     * @return float|null
     */
    public function getDamagePerShot()
    {
        return $this->container['damage_per_shot'];
    }

    /**
     * Sets damage_per_shot
     *
     * @param float|null $damage_per_shot damage_per_shot
     *
     * @return self
     */
    public function setDamagePerShot($damage_per_shot)
    {
        if (is_null($damage_per_shot)) {
            throw new \InvalidArgumentException('non-nullable damage_per_shot cannot be null');
        }
        $this->container['damage_per_shot'] = $damage_per_shot;

        return $this;
    }

    /**
     * Gets average_damage_per_round
     *
     * @return float|null
     */
    public function getAverageDamagePerRound()
    {
        return $this->container['average_damage_per_round'];
    }

    /**
     * Sets average_damage_per_round
     *
     * @param float|null $average_damage_per_round average_damage_per_round
     *
     * @return self
     */
    public function setAverageDamagePerRound($average_damage_per_round)
    {
        if (is_null($average_damage_per_round)) {
            throw new \InvalidArgumentException('non-nullable average_damage_per_round cannot be null');
        }
        $this->container['average_damage_per_round'] = $average_damage_per_round;

        return $this;
    }

    /**
     * Gets opening_kills
     *
     * @return int|null
     */
    public function getOpeningKills()
    {
        return $this->container['opening_kills'];
    }

    /**
     * Sets opening_kills
     *
     * @param int|null $opening_kills opening_kills
     *
     * @return self
     */
    public function setOpeningKills($opening_kills)
    {
        if (is_null($opening_kills)) {
            throw new \InvalidArgumentException('non-nullable opening_kills cannot be null');
        }
        $this->container['opening_kills'] = $opening_kills;

        return $this;
    }

    /**
     * Gets opening_deaths
     *
     * @return int|null
     */
    public function getOpeningDeaths()
    {
        return $this->container['opening_deaths'];
    }

    /**
     * Sets opening_deaths
     *
     * @param int|null $opening_deaths opening_deaths
     *
     * @return self
     */
    public function setOpeningDeaths($opening_deaths)
    {
        if (is_null($opening_deaths)) {
            throw new \InvalidArgumentException('non-nullable opening_deaths cannot be null');
        }
        $this->container['opening_deaths'] = $opening_deaths;

        return $this;
    }

    /**
     * Gets first_kills
     *
     * @return int|null
     */
    public function getFirstKills()
    {
        return $this->container['first_kills'];
    }

    /**
     * Sets first_kills
     *
     * @param int|null $first_kills first_kills
     *
     * @return self
     */
    public function setFirstKills($first_kills)
    {
        if (is_null($first_kills)) {
            throw new \InvalidArgumentException('non-nullable first_kills cannot be null');
        }
        $this->container['first_kills'] = $first_kills;

        return $this;
    }

    /**
     * Gets first_deaths
     *
     * @return int|null
     */
    public function getFirstDeaths()
    {
        return $this->container['first_deaths'];
    }

    /**
     * Sets first_deaths
     *
     * @param int|null $first_deaths first_deaths
     *
     * @return self
     */
    public function setFirstDeaths($first_deaths)
    {
        if (is_null($first_deaths)) {
            throw new \InvalidArgumentException('non-nullable first_deaths cannot be null');
        }
        $this->container['first_deaths'] = $first_deaths;

        return $this;
    }

    /**
     * Gets rounds_2k
     *
     * @return int|null
     */
    public function getRounds2k()
    {
        return $this->container['rounds_2k'];
    }

    /**
     * Sets rounds_2k
     *
     * @param int|null $rounds_2k rounds_2k
     *
     * @return self
     */
    public function setRounds2k($rounds_2k)
    {
        if (is_null($rounds_2k)) {
            throw new \InvalidArgumentException('non-nullable rounds_2k cannot be null');
        }
        $this->container['rounds_2k'] = $rounds_2k;

        return $this;
    }

    /**
     * Gets rounds_3k
     *
     * @return int|null
     */
    public function getRounds3k()
    {
        return $this->container['rounds_3k'];
    }

    /**
     * Sets rounds_3k
     *
     * @param int|null $rounds_3k rounds_3k
     *
     * @return self
     */
    public function setRounds3k($rounds_3k)
    {
        if (is_null($rounds_3k)) {
            throw new \InvalidArgumentException('non-nullable rounds_3k cannot be null');
        }
        $this->container['rounds_3k'] = $rounds_3k;

        return $this;
    }

    /**
     * Gets rounds_4k
     *
     * @return int|null
     */
    public function getRounds4k()
    {
        return $this->container['rounds_4k'];
    }

    /**
     * Sets rounds_4k
     *
     * @param int|null $rounds_4k rounds_4k
     *
     * @return self
     */
    public function setRounds4k($rounds_4k)
    {
        if (is_null($rounds_4k)) {
            throw new \InvalidArgumentException('non-nullable rounds_4k cannot be null');
        }
        $this->container['rounds_4k'] = $rounds_4k;

        return $this;
    }

    /**
     * Gets rounds_5k
     *
     * @return int|null
     */
    public function getRounds5k()
    {
        return $this->container['rounds_5k'];
    }

    /**
     * Sets rounds_5k
     *
     * @param int|null $rounds_5k rounds_5k
     *
     * @return self
     */
    public function setRounds5k($rounds_5k)
    {
        if (is_null($rounds_5k)) {
            throw new \InvalidArgumentException('non-nullable rounds_5k cannot be null');
        }
        $this->container['rounds_5k'] = $rounds_5k;

        return $this;
    }

    /**
     * Gets rounds_ace
     *
     * @return int|null
     */
    public function getRoundsAce()
    {
        return $this->container['rounds_ace'];
    }

    /**
     * Sets rounds_ace
     *
     * @param int|null $rounds_ace rounds_ace
     *
     * @return self
     */
    public function setRoundsAce($rounds_ace)
    {
        if (is_null($rounds_ace)) {
            throw new \InvalidArgumentException('non-nullable rounds_ace cannot be null');
        }
        $this->container['rounds_ace'] = $rounds_ace;

        return $this;
    }

    /**
     * Gets clutch_1v1_attempts
     *
     * @return int|null
     */
    public function getClutch1v1Attempts()
    {
        return $this->container['clutch_1v1_attempts'];
    }

    /**
     * Sets clutch_1v1_attempts
     *
     * @param int|null $clutch_1v1_attempts clutch_1v1_attempts
     *
     * @return self
     */
    public function setClutch1v1Attempts($clutch_1v1_attempts)
    {
        if (is_null($clutch_1v1_attempts)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v1_attempts cannot be null');
        }
        $this->container['clutch_1v1_attempts'] = $clutch_1v1_attempts;

        return $this;
    }

    /**
     * Gets clutch_1v1_won
     *
     * @return int|null
     */
    public function getClutch1v1Won()
    {
        return $this->container['clutch_1v1_won'];
    }

    /**
     * Sets clutch_1v1_won
     *
     * @param int|null $clutch_1v1_won clutch_1v1_won
     *
     * @return self
     */
    public function setClutch1v1Won($clutch_1v1_won)
    {
        if (is_null($clutch_1v1_won)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v1_won cannot be null');
        }
        $this->container['clutch_1v1_won'] = $clutch_1v1_won;

        return $this;
    }

    /**
     * Gets clutch_1v1_saved
     *
     * @return int|null
     */
    public function getClutch1v1Saved()
    {
        return $this->container['clutch_1v1_saved'];
    }

    /**
     * Sets clutch_1v1_saved
     *
     * @param int|null $clutch_1v1_saved clutch_1v1_saved
     *
     * @return self
     */
    public function setClutch1v1Saved($clutch_1v1_saved)
    {
        if (is_null($clutch_1v1_saved)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v1_saved cannot be null');
        }
        $this->container['clutch_1v1_saved'] = $clutch_1v1_saved;

        return $this;
    }

    /**
     * Gets clutch_1v2_attempts
     *
     * @return int|null
     */
    public function getClutch1v2Attempts()
    {
        return $this->container['clutch_1v2_attempts'];
    }

    /**
     * Sets clutch_1v2_attempts
     *
     * @param int|null $clutch_1v2_attempts clutch_1v2_attempts
     *
     * @return self
     */
    public function setClutch1v2Attempts($clutch_1v2_attempts)
    {
        if (is_null($clutch_1v2_attempts)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v2_attempts cannot be null');
        }
        $this->container['clutch_1v2_attempts'] = $clutch_1v2_attempts;

        return $this;
    }

    /**
     * Gets clutch_1v2_won
     *
     * @return int|null
     */
    public function getClutch1v2Won()
    {
        return $this->container['clutch_1v2_won'];
    }

    /**
     * Sets clutch_1v2_won
     *
     * @param int|null $clutch_1v2_won clutch_1v2_won
     *
     * @return self
     */
    public function setClutch1v2Won($clutch_1v2_won)
    {
        if (is_null($clutch_1v2_won)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v2_won cannot be null');
        }
        $this->container['clutch_1v2_won'] = $clutch_1v2_won;

        return $this;
    }

    /**
     * Gets clutch_1v2_saved
     *
     * @return int|null
     */
    public function getClutch1v2Saved()
    {
        return $this->container['clutch_1v2_saved'];
    }

    /**
     * Sets clutch_1v2_saved
     *
     * @param int|null $clutch_1v2_saved clutch_1v2_saved
     *
     * @return self
     */
    public function setClutch1v2Saved($clutch_1v2_saved)
    {
        if (is_null($clutch_1v2_saved)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v2_saved cannot be null');
        }
        $this->container['clutch_1v2_saved'] = $clutch_1v2_saved;

        return $this;
    }

    /**
     * Gets clutch_1v3_attempts
     *
     * @return int|null
     */
    public function getClutch1v3Attempts()
    {
        return $this->container['clutch_1v3_attempts'];
    }

    /**
     * Sets clutch_1v3_attempts
     *
     * @param int|null $clutch_1v3_attempts clutch_1v3_attempts
     *
     * @return self
     */
    public function setClutch1v3Attempts($clutch_1v3_attempts)
    {
        if (is_null($clutch_1v3_attempts)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v3_attempts cannot be null');
        }
        $this->container['clutch_1v3_attempts'] = $clutch_1v3_attempts;

        return $this;
    }

    /**
     * Gets clutch_1v3_won
     *
     * @return int|null
     */
    public function getClutch1v3Won()
    {
        return $this->container['clutch_1v3_won'];
    }

    /**
     * Sets clutch_1v3_won
     *
     * @param int|null $clutch_1v3_won clutch_1v3_won
     *
     * @return self
     */
    public function setClutch1v3Won($clutch_1v3_won)
    {
        if (is_null($clutch_1v3_won)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v3_won cannot be null');
        }
        $this->container['clutch_1v3_won'] = $clutch_1v3_won;

        return $this;
    }

    /**
     * Gets clutch_1v3_saved
     *
     * @return int|null
     */
    public function getClutch1v3Saved()
    {
        return $this->container['clutch_1v3_saved'];
    }

    /**
     * Sets clutch_1v3_saved
     *
     * @param int|null $clutch_1v3_saved clutch_1v3_saved
     *
     * @return self
     */
    public function setClutch1v3Saved($clutch_1v3_saved)
    {
        if (is_null($clutch_1v3_saved)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v3_saved cannot be null');
        }
        $this->container['clutch_1v3_saved'] = $clutch_1v3_saved;

        return $this;
    }

    /**
     * Gets clutch_1v4_attempts
     *
     * @return int|null
     */
    public function getClutch1v4Attempts()
    {
        return $this->container['clutch_1v4_attempts'];
    }

    /**
     * Sets clutch_1v4_attempts
     *
     * @param int|null $clutch_1v4_attempts clutch_1v4_attempts
     *
     * @return self
     */
    public function setClutch1v4Attempts($clutch_1v4_attempts)
    {
        if (is_null($clutch_1v4_attempts)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v4_attempts cannot be null');
        }
        $this->container['clutch_1v4_attempts'] = $clutch_1v4_attempts;

        return $this;
    }

    /**
     * Gets clutch_1v4_won
     *
     * @return int|null
     */
    public function getClutch1v4Won()
    {
        return $this->container['clutch_1v4_won'];
    }

    /**
     * Sets clutch_1v4_won
     *
     * @param int|null $clutch_1v4_won clutch_1v4_won
     *
     * @return self
     */
    public function setClutch1v4Won($clutch_1v4_won)
    {
        if (is_null($clutch_1v4_won)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v4_won cannot be null');
        }
        $this->container['clutch_1v4_won'] = $clutch_1v4_won;

        return $this;
    }

    /**
     * Gets clutch_1v4_saved
     *
     * @return int|null
     */
    public function getClutch1v4Saved()
    {
        return $this->container['clutch_1v4_saved'];
    }

    /**
     * Sets clutch_1v4_saved
     *
     * @param int|null $clutch_1v4_saved clutch_1v4_saved
     *
     * @return self
     */
    public function setClutch1v4Saved($clutch_1v4_saved)
    {
        if (is_null($clutch_1v4_saved)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v4_saved cannot be null');
        }
        $this->container['clutch_1v4_saved'] = $clutch_1v4_saved;

        return $this;
    }

    /**
     * Gets clutch_1v5_attempts
     *
     * @return int|null
     */
    public function getClutch1v5Attempts()
    {
        return $this->container['clutch_1v5_attempts'];
    }

    /**
     * Sets clutch_1v5_attempts
     *
     * @param int|null $clutch_1v5_attempts clutch_1v5_attempts
     *
     * @return self
     */
    public function setClutch1v5Attempts($clutch_1v5_attempts)
    {
        if (is_null($clutch_1v5_attempts)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v5_attempts cannot be null');
        }
        $this->container['clutch_1v5_attempts'] = $clutch_1v5_attempts;

        return $this;
    }

    /**
     * Gets clutch_1v5_won
     *
     * @return int|null
     */
    public function getClutch1v5Won()
    {
        return $this->container['clutch_1v5_won'];
    }

    /**
     * Sets clutch_1v5_won
     *
     * @param int|null $clutch_1v5_won clutch_1v5_won
     *
     * @return self
     */
    public function setClutch1v5Won($clutch_1v5_won)
    {
        if (is_null($clutch_1v5_won)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v5_won cannot be null');
        }
        $this->container['clutch_1v5_won'] = $clutch_1v5_won;

        return $this;
    }

    /**
     * Gets clutch_1v5_saved
     *
     * @return int|null
     */
    public function getClutch1v5Saved()
    {
        return $this->container['clutch_1v5_saved'];
    }

    /**
     * Sets clutch_1v5_saved
     *
     * @param int|null $clutch_1v5_saved clutch_1v5_saved
     *
     * @return self
     */
    public function setClutch1v5Saved($clutch_1v5_saved)
    {
        if (is_null($clutch_1v5_saved)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v5_saved cannot be null');
        }
        $this->container['clutch_1v5_saved'] = $clutch_1v5_saved;

        return $this;
    }

    /**
     * Gets average_equipment_value
     *
     * @return float|null
     */
    public function getAverageEquipmentValue()
    {
        return $this->container['average_equipment_value'];
    }

    /**
     * Sets average_equipment_value
     *
     * @param float|null $average_equipment_value average_equipment_value
     *
     * @return self
     */
    public function setAverageEquipmentValue($average_equipment_value)
    {
        if (is_null($average_equipment_value)) {
            throw new \InvalidArgumentException('non-nullable average_equipment_value cannot be null');
        }
        $this->container['average_equipment_value'] = $average_equipment_value;

        return $this;
    }

    /**
     * Gets total_cash_spent
     *
     * @return int|null
     */
    public function getTotalCashSpent()
    {
        return $this->container['total_cash_spent'];
    }

    /**
     * Sets total_cash_spent
     *
     * @param int|null $total_cash_spent total_cash_spent
     *
     * @return self
     */
    public function setTotalCashSpent($total_cash_spent)
    {
        if (is_null($total_cash_spent)) {
            throw new \InvalidArgumentException('non-nullable total_cash_spent cannot be null');
        }
        $this->container['total_cash_spent'] = $total_cash_spent;

        return $this;
    }

    /**
     * Gets flashbangs_thrown
     *
     * @return int|null
     */
    public function getFlashbangsThrown()
    {
        return $this->container['flashbangs_thrown'];
    }

    /**
     * Sets flashbangs_thrown
     *
     * @param int|null $flashbangs_thrown flashbangs_thrown
     *
     * @return self
     */
    public function setFlashbangsThrown($flashbangs_thrown)
    {
        if (is_null($flashbangs_thrown)) {
            throw new \InvalidArgumentException('non-nullable flashbangs_thrown cannot be null');
        }
        $this->container['flashbangs_thrown'] = $flashbangs_thrown;

        return $this;
    }

    /**
     * Gets smokes_thrown
     *
     * @return int|null
     */
    public function getSmokesThrown()
    {
        return $this->container['smokes_thrown'];
    }

    /**
     * Sets smokes_thrown
     *
     * @param int|null $smokes_thrown smokes_thrown
     *
     * @return self
     */
    public function setSmokesThrown($smokes_thrown)
    {
        if (is_null($smokes_thrown)) {
            throw new \InvalidArgumentException('non-nullable smokes_thrown cannot be null');
        }
        $this->container['smokes_thrown'] = $smokes_thrown;

        return $this;
    }

    /**
     * Gets he_grenades_thrown
     *
     * @return int|null
     */
    public function getHeGrenadesThrown()
    {
        return $this->container['he_grenades_thrown'];
    }

    /**
     * Sets he_grenades_thrown
     *
     * @param int|null $he_grenades_thrown he_grenades_thrown
     *
     * @return self
     */
    public function setHeGrenadesThrown($he_grenades_thrown)
    {
        if (is_null($he_grenades_thrown)) {
            throw new \InvalidArgumentException('non-nullable he_grenades_thrown cannot be null');
        }
        $this->container['he_grenades_thrown'] = $he_grenades_thrown;

        return $this;
    }

    /**
     * Gets molotovs_thrown
     *
     * @return int|null
     */
    public function getMolotovsThrown()
    {
        return $this->container['molotovs_thrown'];
    }

    /**
     * Sets molotovs_thrown
     *
     * @param int|null $molotovs_thrown molotovs_thrown
     *
     * @return self
     */
    public function setMolotovsThrown($molotovs_thrown)
    {
        if (is_null($molotovs_thrown)) {
            throw new \InvalidArgumentException('non-nullable molotovs_thrown cannot be null');
        }
        $this->container['molotovs_thrown'] = $molotovs_thrown;

        return $this;
    }

    /**
     * Gets enemies_flashed
     *
     * @return int|null
     */
    public function getEnemiesFlashed()
    {
        return $this->container['enemies_flashed'];
    }

    /**
     * Sets enemies_flashed
     *
     * @param int|null $enemies_flashed enemies_flashed
     *
     * @return self
     */
    public function setEnemiesFlashed($enemies_flashed)
    {
        if (is_null($enemies_flashed)) {
            throw new \InvalidArgumentException('non-nullable enemies_flashed cannot be null');
        }
        $this->container['enemies_flashed'] = $enemies_flashed;

        return $this;
    }

    /**
     * Gets shots_fired
     *
     * @return int|null
     */
    public function getShotsFired()
    {
        return $this->container['shots_fired'];
    }

    /**
     * Sets shots_fired
     *
     * @param int|null $shots_fired shots_fired
     *
     * @return self
     */
    public function setShotsFired($shots_fired)
    {
        if (is_null($shots_fired)) {
            throw new \InvalidArgumentException('non-nullable shots_fired cannot be null');
        }
        $this->container['shots_fired'] = $shots_fired;

        return $this;
    }

    /**
     * Gets shots_hit
     *
     * @return int|null
     */
    public function getShotsHit()
    {
        return $this->container['shots_hit'];
    }

    /**
     * Sets shots_hit
     *
     * @param int|null $shots_hit shots_hit
     *
     * @return self
     */
    public function setShotsHit($shots_hit)
    {
        if (is_null($shots_hit)) {
            throw new \InvalidArgumentException('non-nullable shots_hit cannot be null');
        }
        $this->container['shots_hit'] = $shots_hit;

        return $this;
    }

    /**
     * Gets accuracy_percentage
     *
     * @return float|null
     */
    public function getAccuracyPercentage()
    {
        return $this->container['accuracy_percentage'];
    }

    /**
     * Sets accuracy_percentage
     *
     * @param float|null $accuracy_percentage accuracy_percentage
     *
     * @return self
     */
    public function setAccuracyPercentage($accuracy_percentage)
    {
        if (is_null($accuracy_percentage)) {
            throw new \InvalidArgumentException('non-nullable accuracy_percentage cannot be null');
        }
        $this->container['accuracy_percentage'] = $accuracy_percentage;

        return $this;
    }

    /**
     * Gets kd_ratio
     *
     * @return float|null
     */
    public function getKdRatio()
    {
        return $this->container['kd_ratio'];
    }

    /**
     * Sets kd_ratio
     *
     * @param float|null $kd_ratio kd_ratio
     *
     * @return self
     */
    public function setKdRatio($kd_ratio)
    {
        if (is_null($kd_ratio)) {
            throw new \InvalidArgumentException('non-nullable kd_ratio cannot be null');
        }
        $this->container['kd_ratio'] = $kd_ratio;

        return $this;
    }

    /**
     * Gets adr
     *
     * @return float|null
     */
    public function getAdr()
    {
        return $this->container['adr'];
    }

    /**
     * Sets adr
     *
     * @param float|null $adr adr
     *
     * @return self
     */
    public function setAdr($adr)
    {
        if (is_null($adr)) {
            throw new \InvalidArgumentException('non-nullable adr cannot be null');
        }
        $this->container['adr'] = $adr;

        return $this;
    }

    /**
     * Gets kast_percentage
     *
     * @return float|null
     */
    public function getKastPercentage()
    {
        return $this->container['kast_percentage'];
    }

    /**
     * Sets kast_percentage
     *
     * @param float|null $kast_percentage kast_percentage
     *
     * @return self
     */
    public function setKastPercentage($kast_percentage)
    {
        if (is_null($kast_percentage)) {
            throw new \InvalidArgumentException('non-nullable kast_percentage cannot be null');
        }
        $this->container['kast_percentage'] = $kast_percentage;

        return $this;
    }

    /**
     * Gets impact_rating
     *
     * @return float|null
     */
    public function getImpactRating()
    {
        return $this->container['impact_rating'];
    }

    /**
     * Sets impact_rating
     *
     * @param float|null $impact_rating impact_rating
     *
     * @return self
     */
    public function setImpactRating($impact_rating)
    {
        if (is_null($impact_rating)) {
            throw new \InvalidArgumentException('non-nullable impact_rating cannot be null');
        }
        $this->container['impact_rating'] = $impact_rating;

        return $this;
    }

    /**
     * Gets hltv_rating
     *
     * @return float|null
     */
    public function getHltvRating()
    {
        return $this->container['hltv_rating'];
    }

    /**
     * Sets hltv_rating
     *
     * @param float|null $hltv_rating hltv_rating
     *
     * @return self
     */
    public function setHltvRating($hltv_rating)
    {
        if (is_null($hltv_rating)) {
            throw new \InvalidArgumentException('non-nullable hltv_rating cannot be null');
        }
        $this->container['hltv_rating'] = $hltv_rating;

        return $this;
    }

    /**
     * Gets hltv_rating_3
     *
     * @return float|null
     */
    public function getHltvRating3()
    {
        return $this->container['hltv_rating_3'];
    }

    /**
     * Sets hltv_rating_3
     *
     * @param float|null $hltv_rating_3 hltv_rating_3
     *
     * @return self
     */
    public function setHltvRating3($hltv_rating_3)
    {
        if (is_null($hltv_rating_3)) {
            throw new \InvalidArgumentException('non-nullable hltv_rating_3 cannot be null');
        }
        $this->container['hltv_rating_3'] = $hltv_rating_3;

        return $this;
    }

    /**
     * Gets rating
     *
     * @return float|null
     */
    public function getRating()
    {
        return $this->container['rating'];
    }

    /**
     * Sets rating
     *
     * @param float|null $rating rating
     *
     * @return self
     */
    public function setRating($rating)
    {
        if (is_null($rating)) {
            throw new \InvalidArgumentException('non-nullable rating cannot be null');
        }
        $this->container['rating'] = $rating;

        return $this;
    }

    /**
     * Gets personal_performance
     *
     * @return float|null
     */
    public function getPersonalPerformance()
    {
        return $this->container['personal_performance'];
    }

    /**
     * Sets personal_performance
     *
     * @param float|null $personal_performance personal_performance
     *
     * @return self
     */
    public function setPersonalPerformance($personal_performance)
    {
        if (is_null($personal_performance)) {
            throw new \InvalidArgumentException('non-nullable personal_performance cannot be null');
        }
        $this->container['personal_performance'] = $personal_performance;

        return $this;
    }

    /**
     * Gets spotted_accuracy
     *
     * @return float|null
     */
    public function getSpottedAccuracy()
    {
        return $this->container['spotted_accuracy'];
    }

    /**
     * Sets spotted_accuracy
     *
     * @param float|null $spotted_accuracy spotted_accuracy
     *
     * @return self
     */
    public function setSpottedAccuracy($spotted_accuracy)
    {
        if (is_null($spotted_accuracy)) {
            throw new \InvalidArgumentException('non-nullable spotted_accuracy cannot be null');
        }
        $this->container['spotted_accuracy'] = $spotted_accuracy;

        return $this;
    }

    /**
     * Gets time_to_damage_ms
     *
     * @return int|null
     */
    public function getTimeToDamageMs()
    {
        return $this->container['time_to_damage_ms'];
    }

    /**
     * Sets time_to_damage_ms
     *
     * @param int|null $time_to_damage_ms time_to_damage_ms
     *
     * @return self
     */
    public function setTimeToDamageMs($time_to_damage_ms)
    {
        if (is_null($time_to_damage_ms)) {
            throw new \InvalidArgumentException('non-nullable time_to_damage_ms cannot be null');
        }
        $this->container['time_to_damage_ms'] = $time_to_damage_ms;

        return $this;
    }

    /**
     * Gets cross_placement_angle
     *
     * @return float|null
     */
    public function getCrossPlacementAngle()
    {
        return $this->container['cross_placement_angle'];
    }

    /**
     * Sets cross_placement_angle
     *
     * @param float|null $cross_placement_angle cross_placement_angle
     *
     * @return self
     */
    public function setCrossPlacementAngle($cross_placement_angle)
    {
        if (is_null($cross_placement_angle)) {
            throw new \InvalidArgumentException('non-nullable cross_placement_angle cannot be null');
        }
        $this->container['cross_placement_angle'] = $cross_placement_angle;

        return $this;
    }

    /**
     * Gets head_accuracy_pct
     *
     * @return float|null
     */
    public function getHeadAccuracyPct()
    {
        return $this->container['head_accuracy_pct'];
    }

    /**
     * Sets head_accuracy_pct
     *
     * @param float|null $head_accuracy_pct head_accuracy_pct
     *
     * @return self
     */
    public function setHeadAccuracyPct($head_accuracy_pct)
    {
        if (is_null($head_accuracy_pct)) {
            throw new \InvalidArgumentException('non-nullable head_accuracy_pct cannot be null');
        }
        $this->container['head_accuracy_pct'] = $head_accuracy_pct;

        return $this;
    }

    /**
     * Gets spray_accuracy_pct
     *
     * @return float|null
     */
    public function getSprayAccuracyPct()
    {
        return $this->container['spray_accuracy_pct'];
    }

    /**
     * Sets spray_accuracy_pct
     *
     * @param float|null $spray_accuracy_pct spray_accuracy_pct
     *
     * @return self
     */
    public function setSprayAccuracyPct($spray_accuracy_pct)
    {
        if (is_null($spray_accuracy_pct)) {
            throw new \InvalidArgumentException('non-nullable spray_accuracy_pct cannot be null');
        }
        $this->container['spray_accuracy_pct'] = $spray_accuracy_pct;

        return $this;
    }

    /**
     * Gets counter_strafe_quality
     *
     * @return float|null
     */
    public function getCounterStrafeQuality()
    {
        return $this->container['counter_strafe_quality'];
    }

    /**
     * Sets counter_strafe_quality
     *
     * @param float|null $counter_strafe_quality counter_strafe_quality
     *
     * @return self
     */
    public function setCounterStrafeQuality($counter_strafe_quality)
    {
        if (is_null($counter_strafe_quality)) {
            throw new \InvalidArgumentException('non-nullable counter_strafe_quality cannot be null');
        }
        $this->container['counter_strafe_quality'] = $counter_strafe_quality;

        return $this;
    }

    /**
     * Gets pistol_rounds
     *
     * @return int|null
     */
    public function getPistolRounds()
    {
        return $this->container['pistol_rounds'];
    }

    /**
     * Sets pistol_rounds
     *
     * @param int|null $pistol_rounds pistol_rounds
     *
     * @return self
     */
    public function setPistolRounds($pistol_rounds)
    {
        if (is_null($pistol_rounds)) {
            throw new \InvalidArgumentException('non-nullable pistol_rounds cannot be null');
        }
        $this->container['pistol_rounds'] = $pistol_rounds;

        return $this;
    }

    /**
     * Gets eco_rounds
     *
     * @return int|null
     */
    public function getEcoRounds()
    {
        return $this->container['eco_rounds'];
    }

    /**
     * Sets eco_rounds
     *
     * @param int|null $eco_rounds eco_rounds
     *
     * @return self
     */
    public function setEcoRounds($eco_rounds)
    {
        if (is_null($eco_rounds)) {
            throw new \InvalidArgumentException('non-nullable eco_rounds cannot be null');
        }
        $this->container['eco_rounds'] = $eco_rounds;

        return $this;
    }

    /**
     * Gets semi_eco_rounds
     *
     * @return int|null
     */
    public function getSemiEcoRounds()
    {
        return $this->container['semi_eco_rounds'];
    }

    /**
     * Sets semi_eco_rounds
     *
     * @param int|null $semi_eco_rounds semi_eco_rounds
     *
     * @return self
     */
    public function setSemiEcoRounds($semi_eco_rounds)
    {
        if (is_null($semi_eco_rounds)) {
            throw new \InvalidArgumentException('non-nullable semi_eco_rounds cannot be null');
        }
        $this->container['semi_eco_rounds'] = $semi_eco_rounds;

        return $this;
    }

    /**
     * Gets force_buy_rounds
     *
     * @return int|null
     */
    public function getForceBuyRounds()
    {
        return $this->container['force_buy_rounds'];
    }

    /**
     * Sets force_buy_rounds
     *
     * @param int|null $force_buy_rounds force_buy_rounds
     *
     * @return self
     */
    public function setForceBuyRounds($force_buy_rounds)
    {
        if (is_null($force_buy_rounds)) {
            throw new \InvalidArgumentException('non-nullable force_buy_rounds cannot be null');
        }
        $this->container['force_buy_rounds'] = $force_buy_rounds;

        return $this;
    }

    /**
     * Gets full_buy_rounds
     *
     * @return int|null
     */
    public function getFullBuyRounds()
    {
        return $this->container['full_buy_rounds'];
    }

    /**
     * Sets full_buy_rounds
     *
     * @param int|null $full_buy_rounds full_buy_rounds
     *
     * @return self
     */
    public function setFullBuyRounds($full_buy_rounds)
    {
        if (is_null($full_buy_rounds)) {
            throw new \InvalidArgumentException('non-nullable full_buy_rounds cannot be null');
        }
        $this->container['full_buy_rounds'] = $full_buy_rounds;

        return $this;
    }

    /**
     * Gets trade_opportunities
     *
     * @return int|null
     */
    public function getTradeOpportunities()
    {
        return $this->container['trade_opportunities'];
    }

    /**
     * Sets trade_opportunities
     *
     * @param int|null $trade_opportunities trade_opportunities
     *
     * @return self
     */
    public function setTradeOpportunities($trade_opportunities)
    {
        if (is_null($trade_opportunities)) {
            throw new \InvalidArgumentException('non-nullable trade_opportunities cannot be null');
        }
        $this->container['trade_opportunities'] = $trade_opportunities;

        return $this;
    }

    /**
     * Gets trade_attempts
     *
     * @return int|null
     */
    public function getTradeAttempts()
    {
        return $this->container['trade_attempts'];
    }

    /**
     * Sets trade_attempts
     *
     * @param int|null $trade_attempts trade_attempts
     *
     * @return self
     */
    public function setTradeAttempts($trade_attempts)
    {
        if (is_null($trade_attempts)) {
            throw new \InvalidArgumentException('non-nullable trade_attempts cannot be null');
        }
        $this->container['trade_attempts'] = $trade_attempts;

        return $this;
    }

    /**
     * Gets trade_kills
     *
     * @return int|null
     */
    public function getTradeKills()
    {
        return $this->container['trade_kills'];
    }

    /**
     * Sets trade_kills
     *
     * @param int|null $trade_kills trade_kills
     *
     * @return self
     */
    public function setTradeKills($trade_kills)
    {
        if (is_null($trade_kills)) {
            throw new \InvalidArgumentException('non-nullable trade_kills cannot be null');
        }
        $this->container['trade_kills'] = $trade_kills;

        return $this;
    }

    /**
     * Gets trades
     *
     * @return int|null
     */
    public function getTrades()
    {
        return $this->container['trades'];
    }

    /**
     * Sets trades
     *
     * @param int|null $trades trades
     *
     * @return self
     */
    public function setTrades($trades)
    {
        if (is_null($trades)) {
            throw new \InvalidArgumentException('non-nullable trades cannot be null');
        }
        $this->container['trades'] = $trades;

        return $this;
    }

    /**
     * Gets was_traded
     *
     * @return int|null
     */
    public function getWasTraded()
    {
        return $this->container['was_traded'];
    }

    /**
     * Sets was_traded
     *
     * @param int|null $was_traded was_traded
     *
     * @return self
     */
    public function setWasTraded($was_traded)
    {
        if (is_null($was_traded)) {
            throw new \InvalidArgumentException('non-nullable was_traded cannot be null');
        }
        $this->container['was_traded'] = $was_traded;

        return $this;
    }

    /**
     * Gets trade_kill_opportunities
     *
     * @return int|null
     */
    public function getTradeKillOpportunities()
    {
        return $this->container['trade_kill_opportunities'];
    }

    /**
     * Sets trade_kill_opportunities
     *
     * @param int|null $trade_kill_opportunities trade_kill_opportunities
     *
     * @return self
     */
    public function setTradeKillOpportunities($trade_kill_opportunities)
    {
        if (is_null($trade_kill_opportunities)) {
            throw new \InvalidArgumentException('non-nullable trade_kill_opportunities cannot be null');
        }
        $this->container['trade_kill_opportunities'] = $trade_kill_opportunities;

        return $this;
    }

    /**
     * Gets trade_kill_attempts
     *
     * @return int|null
     */
    public function getTradeKillAttempts()
    {
        return $this->container['trade_kill_attempts'];
    }

    /**
     * Sets trade_kill_attempts
     *
     * @param int|null $trade_kill_attempts trade_kill_attempts
     *
     * @return self
     */
    public function setTradeKillAttempts($trade_kill_attempts)
    {
        if (is_null($trade_kill_attempts)) {
            throw new \InvalidArgumentException('non-nullable trade_kill_attempts cannot be null');
        }
        $this->container['trade_kill_attempts'] = $trade_kill_attempts;

        return $this;
    }

    /**
     * Gets trade_kill_success
     *
     * @return int|null
     */
    public function getTradeKillSuccess()
    {
        return $this->container['trade_kill_success'];
    }

    /**
     * Sets trade_kill_success
     *
     * @param int|null $trade_kill_success trade_kill_success
     *
     * @return self
     */
    public function setTradeKillSuccess($trade_kill_success)
    {
        if (is_null($trade_kill_success)) {
            throw new \InvalidArgumentException('non-nullable trade_kill_success cannot be null');
        }
        $this->container['trade_kill_success'] = $trade_kill_success;

        return $this;
    }

    /**
     * Gets trade_death_opportunities
     *
     * @return int|null
     */
    public function getTradeDeathOpportunities()
    {
        return $this->container['trade_death_opportunities'];
    }

    /**
     * Sets trade_death_opportunities
     *
     * @param int|null $trade_death_opportunities trade_death_opportunities
     *
     * @return self
     */
    public function setTradeDeathOpportunities($trade_death_opportunities)
    {
        if (is_null($trade_death_opportunities)) {
            throw new \InvalidArgumentException('non-nullable trade_death_opportunities cannot be null');
        }
        $this->container['trade_death_opportunities'] = $trade_death_opportunities;

        return $this;
    }

    /**
     * Gets trade_death_attempts
     *
     * @return int|null
     */
    public function getTradeDeathAttempts()
    {
        return $this->container['trade_death_attempts'];
    }

    /**
     * Sets trade_death_attempts
     *
     * @param int|null $trade_death_attempts trade_death_attempts
     *
     * @return self
     */
    public function setTradeDeathAttempts($trade_death_attempts)
    {
        if (is_null($trade_death_attempts)) {
            throw new \InvalidArgumentException('non-nullable trade_death_attempts cannot be null');
        }
        $this->container['trade_death_attempts'] = $trade_death_attempts;

        return $this;
    }

    /**
     * Gets trade_death_success
     *
     * @return int|null
     */
    public function getTradeDeathSuccess()
    {
        return $this->container['trade_death_success'];
    }

    /**
     * Sets trade_death_success
     *
     * @param int|null $trade_death_success trade_death_success
     *
     * @return self
     */
    public function setTradeDeathSuccess($trade_death_success)
    {
        if (is_null($trade_death_success)) {
            throw new \InvalidArgumentException('non-nullable trade_death_success cannot be null');
        }
        $this->container['trade_death_success'] = $trade_death_success;

        return $this;
    }

    /**
     * Gets teammates_flashed
     *
     * @return int|null
     */
    public function getTeammatesFlashed()
    {
        return $this->container['teammates_flashed'];
    }

    /**
     * Sets teammates_flashed
     *
     * @param int|null $teammates_flashed teammates_flashed
     *
     * @return self
     */
    public function setTeammatesFlashed($teammates_flashed)
    {
        if (is_null($teammates_flashed)) {
            throw new \InvalidArgumentException('non-nullable teammates_flashed cannot be null');
        }
        $this->container['teammates_flashed'] = $teammates_flashed;

        return $this;
    }

    /**
     * Gets flash_assists
     *
     * @return int|null
     */
    public function getFlashAssists()
    {
        return $this->container['flash_assists'];
    }

    /**
     * Sets flash_assists
     *
     * @param int|null $flash_assists flash_assists
     *
     * @return self
     */
    public function setFlashAssists($flash_assists)
    {
        if (is_null($flash_assists)) {
            throw new \InvalidArgumentException('non-nullable flash_assists cannot be null');
        }
        $this->container['flash_assists'] = $flash_assists;

        return $this;
    }

    /**
     * Gets avg_blind_time
     *
     * @return float|null
     */
    public function getAvgBlindTime()
    {
        return $this->container['avg_blind_time'];
    }

    /**
     * Sets avg_blind_time
     *
     * @param float|null $avg_blind_time avg_blind_time
     *
     * @return self
     */
    public function setAvgBlindTime($avg_blind_time)
    {
        if (is_null($avg_blind_time)) {
            throw new \InvalidArgumentException('non-nullable avg_blind_time cannot be null');
        }
        $this->container['avg_blind_time'] = $avg_blind_time;

        return $this;
    }

    /**
     * Gets enemies_blind_time
     *
     * @return float|null
     */
    public function getEnemiesBlindTime()
    {
        return $this->container['enemies_blind_time'];
    }

    /**
     * Sets enemies_blind_time
     *
     * @param float|null $enemies_blind_time enemies_blind_time
     *
     * @return self
     */
    public function setEnemiesBlindTime($enemies_blind_time)
    {
        if (is_null($enemies_blind_time)) {
            throw new \InvalidArgumentException('non-nullable enemies_blind_time cannot be null');
        }
        $this->container['enemies_blind_time'] = $enemies_blind_time;

        return $this;
    }

    /**
     * Gets avg_he_damage
     *
     * @return float|null
     */
    public function getAvgHeDamage()
    {
        return $this->container['avg_he_damage'];
    }

    /**
     * Sets avg_he_damage
     *
     * @param float|null $avg_he_damage avg_he_damage
     *
     * @return self
     */
    public function setAvgHeDamage($avg_he_damage)
    {
        if (is_null($avg_he_damage)) {
            throw new \InvalidArgumentException('non-nullable avg_he_damage cannot be null');
        }
        $this->container['avg_he_damage'] = $avg_he_damage;

        return $this;
    }

    /**
     * Gets unused_utility_value
     *
     * @return int|null
     */
    public function getUnusedUtilityValue()
    {
        return $this->container['unused_utility_value'];
    }

    /**
     * Sets unused_utility_value
     *
     * @param int|null $unused_utility_value unused_utility_value
     *
     * @return self
     */
    public function setUnusedUtilityValue($unused_utility_value)
    {
        if (is_null($unused_utility_value)) {
            throw new \InvalidArgumentException('non-nullable unused_utility_value cannot be null');
        }
        $this->container['unused_utility_value'] = $unused_utility_value;

        return $this;
    }

    /**
     * Gets opening_duel_attempt_rate
     *
     * @return float|null
     */
    public function getOpeningDuelAttemptRate()
    {
        return $this->container['opening_duel_attempt_rate'];
    }

    /**
     * Sets opening_duel_attempt_rate
     *
     * @param float|null $opening_duel_attempt_rate opening_duel_attempt_rate
     *
     * @return self
     */
    public function setOpeningDuelAttemptRate($opening_duel_attempt_rate)
    {
        if (is_null($opening_duel_attempt_rate)) {
            throw new \InvalidArgumentException('non-nullable opening_duel_attempt_rate cannot be null');
        }
        $this->container['opening_duel_attempt_rate'] = $opening_duel_attempt_rate;

        return $this;
    }

    /**
     * Gets opening_duel_success_rate
     *
     * @return float|null
     */
    public function getOpeningDuelSuccessRate()
    {
        return $this->container['opening_duel_success_rate'];
    }

    /**
     * Sets opening_duel_success_rate
     *
     * @param float|null $opening_duel_success_rate opening_duel_success_rate
     *
     * @return self
     */
    public function setOpeningDuelSuccessRate($opening_duel_success_rate)
    {
        if (is_null($opening_duel_success_rate)) {
            throw new \InvalidArgumentException('non-nullable opening_duel_success_rate cannot be null');
        }
        $this->container['opening_duel_success_rate'] = $opening_duel_success_rate;

        return $this;
    }

    /**
     * Gets aim_score
     *
     * @return float|null
     */
    public function getAimScore()
    {
        return $this->container['aim_score'];
    }

    /**
     * Sets aim_score
     *
     * @param float|null $aim_score aim_score
     *
     * @return self
     */
    public function setAimScore($aim_score)
    {
        if (is_null($aim_score)) {
            throw new \InvalidArgumentException('non-nullable aim_score cannot be null');
        }
        $this->container['aim_score'] = $aim_score;

        return $this;
    }

    /**
     * Gets utility_score
     *
     * @return float|null
     */
    public function getUtilityScore()
    {
        return $this->container['utility_score'];
    }

    /**
     * Sets utility_score
     *
     * @param float|null $utility_score utility_score
     *
     * @return self
     */
    public function setUtilityScore($utility_score)
    {
        if (is_null($utility_score)) {
            throw new \InvalidArgumentException('non-nullable utility_score cannot be null');
        }
        $this->container['utility_score'] = $utility_score;

        return $this;
    }

    /**
     * Gets positioning_score
     *
     * @return float|null
     */
    public function getPositioningScore()
    {
        return $this->container['positioning_score'];
    }

    /**
     * Sets positioning_score
     *
     * @param float|null $positioning_score positioning_score
     *
     * @return self
     */
    public function setPositioningScore($positioning_score)
    {
        if (is_null($positioning_score)) {
            throw new \InvalidArgumentException('non-nullable positioning_score cannot be null');
        }
        $this->container['positioning_score'] = $positioning_score;

        return $this;
    }

    /**
     * Gets rounds_as_t
     *
     * @return int|null
     */
    public function getRoundsAsT()
    {
        return $this->container['rounds_as_t'];
    }

    /**
     * Sets rounds_as_t
     *
     * @param int|null $rounds_as_t rounds_as_t
     *
     * @return self
     */
    public function setRoundsAsT($rounds_as_t)
    {
        if (is_null($rounds_as_t)) {
            throw new \InvalidArgumentException('non-nullable rounds_as_t cannot be null');
        }
        $this->container['rounds_as_t'] = $rounds_as_t;

        return $this;
    }

    /**
     * Gets rounds_as_ct
     *
     * @return int|null
     */
    public function getRoundsAsCt()
    {
        return $this->container['rounds_as_ct'];
    }

    /**
     * Sets rounds_as_ct
     *
     * @param int|null $rounds_as_ct rounds_as_ct
     *
     * @return self
     */
    public function setRoundsAsCt($rounds_as_ct)
    {
        if (is_null($rounds_as_ct)) {
            throw new \InvalidArgumentException('non-nullable rounds_as_ct cannot be null');
        }
        $this->container['rounds_as_ct'] = $rounds_as_ct;

        return $this;
    }

    /**
     * Gets kills_as_t
     *
     * @return int|null
     */
    public function getKillsAsT()
    {
        return $this->container['kills_as_t'];
    }

    /**
     * Sets kills_as_t
     *
     * @param int|null $kills_as_t kills_as_t
     *
     * @return self
     */
    public function setKillsAsT($kills_as_t)
    {
        if (is_null($kills_as_t)) {
            throw new \InvalidArgumentException('non-nullable kills_as_t cannot be null');
        }
        $this->container['kills_as_t'] = $kills_as_t;

        return $this;
    }

    /**
     * Gets kills_as_ct
     *
     * @return int|null
     */
    public function getKillsAsCt()
    {
        return $this->container['kills_as_ct'];
    }

    /**
     * Sets kills_as_ct
     *
     * @param int|null $kills_as_ct kills_as_ct
     *
     * @return self
     */
    public function setKillsAsCt($kills_as_ct)
    {
        if (is_null($kills_as_ct)) {
            throw new \InvalidArgumentException('non-nullable kills_as_ct cannot be null');
        }
        $this->container['kills_as_ct'] = $kills_as_ct;

        return $this;
    }

    /**
     * Gets deaths_as_t
     *
     * @return int|null
     */
    public function getDeathsAsT()
    {
        return $this->container['deaths_as_t'];
    }

    /**
     * Sets deaths_as_t
     *
     * @param int|null $deaths_as_t deaths_as_t
     *
     * @return self
     */
    public function setDeathsAsT($deaths_as_t)
    {
        if (is_null($deaths_as_t)) {
            throw new \InvalidArgumentException('non-nullable deaths_as_t cannot be null');
        }
        $this->container['deaths_as_t'] = $deaths_as_t;

        return $this;
    }

    /**
     * Gets deaths_as_ct
     *
     * @return int|null
     */
    public function getDeathsAsCt()
    {
        return $this->container['deaths_as_ct'];
    }

    /**
     * Sets deaths_as_ct
     *
     * @param int|null $deaths_as_ct deaths_as_ct
     *
     * @return self
     */
    public function setDeathsAsCt($deaths_as_ct)
    {
        if (is_null($deaths_as_ct)) {
            throw new \InvalidArgumentException('non-nullable deaths_as_ct cannot be null');
        }
        $this->container['deaths_as_ct'] = $deaths_as_ct;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


