<?php
/**
 * UserMatchResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NoScope API
 *
 * Publicly available API for the NoScope platform. Requires authentication for all endpoints. Get your API key from the NoScope dashboard. API Rate Limiting applies to all endpoints and are currently capped at 100 requests per hour. Request api access at <a href='https://CSSkill.com/api'>https://CSSkill.com/api</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@CSSkill.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * UserMatchResponse Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UserMatchResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UserMatchResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'match_date' => 'string',
        'match_type' => 'string',
        'match_map' => 'string',
        'match_duration' => 'int',
        'won' => 'bool',
        'kills' => 'int',
        'deaths' => 'int',
        'assists' => 'int',
        'headshots' => 'int',
        'damage' => 'int',
        'mvps' => 'int',
        'kd_ratio' => 'float',
        'adr' => 'float',
        'hltv2_rating' => 'float',
        'hltv3_rating' => 'float',
        'rating' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'match_date' => null,
        'match_type' => null,
        'match_map' => null,
        'match_duration' => null,
        'won' => null,
        'kills' => null,
        'deaths' => null,
        'assists' => null,
        'headshots' => null,
        'damage' => null,
        'mvps' => null,
        'kd_ratio' => 'float',
        'adr' => 'float',
        'hltv2_rating' => 'float',
        'hltv3_rating' => 'float',
        'rating' => 'float'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'match_date' => false,
        'match_type' => false,
        'match_map' => false,
        'match_duration' => false,
        'won' => false,
        'kills' => false,
        'deaths' => false,
        'assists' => false,
        'headshots' => false,
        'damage' => false,
        'mvps' => false,
        'kd_ratio' => false,
        'adr' => false,
        'hltv2_rating' => false,
        'hltv3_rating' => false,
        'rating' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'match_date' => 'match_date',
        'match_type' => 'match_type',
        'match_map' => 'match_map',
        'match_duration' => 'match_duration',
        'won' => 'won',
        'kills' => 'kills',
        'deaths' => 'deaths',
        'assists' => 'assists',
        'headshots' => 'headshots',
        'damage' => 'damage',
        'mvps' => 'mvps',
        'kd_ratio' => 'kd_ratio',
        'adr' => 'adr',
        'hltv2_rating' => 'hltv2_rating',
        'hltv3_rating' => 'hltv3_rating',
        'rating' => 'rating'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'match_date' => 'setMatchDate',
        'match_type' => 'setMatchType',
        'match_map' => 'setMatchMap',
        'match_duration' => 'setMatchDuration',
        'won' => 'setWon',
        'kills' => 'setKills',
        'deaths' => 'setDeaths',
        'assists' => 'setAssists',
        'headshots' => 'setHeadshots',
        'damage' => 'setDamage',
        'mvps' => 'setMvps',
        'kd_ratio' => 'setKdRatio',
        'adr' => 'setAdr',
        'hltv2_rating' => 'setHltv2Rating',
        'hltv3_rating' => 'setHltv3Rating',
        'rating' => 'setRating'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'match_date' => 'getMatchDate',
        'match_type' => 'getMatchType',
        'match_map' => 'getMatchMap',
        'match_duration' => 'getMatchDuration',
        'won' => 'getWon',
        'kills' => 'getKills',
        'deaths' => 'getDeaths',
        'assists' => 'getAssists',
        'headshots' => 'getHeadshots',
        'damage' => 'getDamage',
        'mvps' => 'getMvps',
        'kd_ratio' => 'getKdRatio',
        'adr' => 'getAdr',
        'hltv2_rating' => 'getHltv2Rating',
        'hltv3_rating' => 'getHltv3Rating',
        'rating' => 'getRating'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('match_date', $data ?? [], null);
        $this->setIfExists('match_type', $data ?? [], null);
        $this->setIfExists('match_map', $data ?? [], null);
        $this->setIfExists('match_duration', $data ?? [], null);
        $this->setIfExists('won', $data ?? [], null);
        $this->setIfExists('kills', $data ?? [], null);
        $this->setIfExists('deaths', $data ?? [], null);
        $this->setIfExists('assists', $data ?? [], null);
        $this->setIfExists('headshots', $data ?? [], null);
        $this->setIfExists('damage', $data ?? [], null);
        $this->setIfExists('mvps', $data ?? [], null);
        $this->setIfExists('kd_ratio', $data ?? [], null);
        $this->setIfExists('adr', $data ?? [], null);
        $this->setIfExists('hltv2_rating', $data ?? [], null);
        $this->setIfExists('hltv3_rating', $data ?? [], null);
        $this->setIfExists('rating', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets match_date
     *
     * @return string|null
     */
    public function getMatchDate()
    {
        return $this->container['match_date'];
    }

    /**
     * Sets match_date
     *
     * @param string|null $match_date match_date
     *
     * @return self
     */
    public function setMatchDate($match_date)
    {
        if (is_null($match_date)) {
            throw new \InvalidArgumentException('non-nullable match_date cannot be null');
        }
        $this->container['match_date'] = $match_date;

        return $this;
    }

    /**
     * Gets match_type
     *
     * @return string|null
     */
    public function getMatchType()
    {
        return $this->container['match_type'];
    }

    /**
     * Sets match_type
     *
     * @param string|null $match_type match_type
     *
     * @return self
     */
    public function setMatchType($match_type)
    {
        if (is_null($match_type)) {
            throw new \InvalidArgumentException('non-nullable match_type cannot be null');
        }
        $this->container['match_type'] = $match_type;

        return $this;
    }

    /**
     * Gets match_map
     *
     * @return string|null
     */
    public function getMatchMap()
    {
        return $this->container['match_map'];
    }

    /**
     * Sets match_map
     *
     * @param string|null $match_map match_map
     *
     * @return self
     */
    public function setMatchMap($match_map)
    {
        if (is_null($match_map)) {
            throw new \InvalidArgumentException('non-nullable match_map cannot be null');
        }
        $this->container['match_map'] = $match_map;

        return $this;
    }

    /**
     * Gets match_duration
     *
     * @return int|null
     */
    public function getMatchDuration()
    {
        return $this->container['match_duration'];
    }

    /**
     * Sets match_duration
     *
     * @param int|null $match_duration match_duration
     *
     * @return self
     */
    public function setMatchDuration($match_duration)
    {
        if (is_null($match_duration)) {
            throw new \InvalidArgumentException('non-nullable match_duration cannot be null');
        }
        $this->container['match_duration'] = $match_duration;

        return $this;
    }

    /**
     * Gets won
     *
     * @return bool|null
     */
    public function getWon()
    {
        return $this->container['won'];
    }

    /**
     * Sets won
     *
     * @param bool|null $won won
     *
     * @return self
     */
    public function setWon($won)
    {
        if (is_null($won)) {
            throw new \InvalidArgumentException('non-nullable won cannot be null');
        }
        $this->container['won'] = $won;

        return $this;
    }

    /**
     * Gets kills
     *
     * @return int|null
     */
    public function getKills()
    {
        return $this->container['kills'];
    }

    /**
     * Sets kills
     *
     * @param int|null $kills kills
     *
     * @return self
     */
    public function setKills($kills)
    {
        if (is_null($kills)) {
            throw new \InvalidArgumentException('non-nullable kills cannot be null');
        }
        $this->container['kills'] = $kills;

        return $this;
    }

    /**
     * Gets deaths
     *
     * @return int|null
     */
    public function getDeaths()
    {
        return $this->container['deaths'];
    }

    /**
     * Sets deaths
     *
     * @param int|null $deaths deaths
     *
     * @return self
     */
    public function setDeaths($deaths)
    {
        if (is_null($deaths)) {
            throw new \InvalidArgumentException('non-nullable deaths cannot be null');
        }
        $this->container['deaths'] = $deaths;

        return $this;
    }

    /**
     * Gets assists
     *
     * @return int|null
     */
    public function getAssists()
    {
        return $this->container['assists'];
    }

    /**
     * Sets assists
     *
     * @param int|null $assists assists
     *
     * @return self
     */
    public function setAssists($assists)
    {
        if (is_null($assists)) {
            throw new \InvalidArgumentException('non-nullable assists cannot be null');
        }
        $this->container['assists'] = $assists;

        return $this;
    }

    /**
     * Gets headshots
     *
     * @return int|null
     */
    public function getHeadshots()
    {
        return $this->container['headshots'];
    }

    /**
     * Sets headshots
     *
     * @param int|null $headshots headshots
     *
     * @return self
     */
    public function setHeadshots($headshots)
    {
        if (is_null($headshots)) {
            throw new \InvalidArgumentException('non-nullable headshots cannot be null');
        }
        $this->container['headshots'] = $headshots;

        return $this;
    }

    /**
     * Gets damage
     *
     * @return int|null
     */
    public function getDamage()
    {
        return $this->container['damage'];
    }

    /**
     * Sets damage
     *
     * @param int|null $damage damage
     *
     * @return self
     */
    public function setDamage($damage)
    {
        if (is_null($damage)) {
            throw new \InvalidArgumentException('non-nullable damage cannot be null');
        }
        $this->container['damage'] = $damage;

        return $this;
    }

    /**
     * Gets mvps
     *
     * @return int|null
     */
    public function getMvps()
    {
        return $this->container['mvps'];
    }

    /**
     * Sets mvps
     *
     * @param int|null $mvps mvps
     *
     * @return self
     */
    public function setMvps($mvps)
    {
        if (is_null($mvps)) {
            throw new \InvalidArgumentException('non-nullable mvps cannot be null');
        }
        $this->container['mvps'] = $mvps;

        return $this;
    }

    /**
     * Gets kd_ratio
     *
     * @return float|null
     */
    public function getKdRatio()
    {
        return $this->container['kd_ratio'];
    }

    /**
     * Sets kd_ratio
     *
     * @param float|null $kd_ratio kd_ratio
     *
     * @return self
     */
    public function setKdRatio($kd_ratio)
    {
        if (is_null($kd_ratio)) {
            throw new \InvalidArgumentException('non-nullable kd_ratio cannot be null');
        }
        $this->container['kd_ratio'] = $kd_ratio;

        return $this;
    }

    /**
     * Gets adr
     *
     * @return float|null
     */
    public function getAdr()
    {
        return $this->container['adr'];
    }

    /**
     * Sets adr
     *
     * @param float|null $adr adr
     *
     * @return self
     */
    public function setAdr($adr)
    {
        if (is_null($adr)) {
            throw new \InvalidArgumentException('non-nullable adr cannot be null');
        }
        $this->container['adr'] = $adr;

        return $this;
    }

    /**
     * Gets hltv2_rating
     *
     * @return float|null
     */
    public function getHltv2Rating()
    {
        return $this->container['hltv2_rating'];
    }

    /**
     * Sets hltv2_rating
     *
     * @param float|null $hltv2_rating hltv2_rating
     *
     * @return self
     */
    public function setHltv2Rating($hltv2_rating)
    {
        if (is_null($hltv2_rating)) {
            throw new \InvalidArgumentException('non-nullable hltv2_rating cannot be null');
        }
        $this->container['hltv2_rating'] = $hltv2_rating;

        return $this;
    }

    /**
     * Gets hltv3_rating
     *
     * @return float|null
     */
    public function getHltv3Rating()
    {
        return $this->container['hltv3_rating'];
    }

    /**
     * Sets hltv3_rating
     *
     * @param float|null $hltv3_rating hltv3_rating
     *
     * @return self
     */
    public function setHltv3Rating($hltv3_rating)
    {
        if (is_null($hltv3_rating)) {
            throw new \InvalidArgumentException('non-nullable hltv3_rating cannot be null');
        }
        $this->container['hltv3_rating'] = $hltv3_rating;

        return $this;
    }

    /**
     * Gets rating
     *
     * @return float|null
     */
    public function getRating()
    {
        return $this->container['rating'];
    }

    /**
     * Sets rating
     *
     * @param float|null $rating rating
     *
     * @return self
     */
    public function setRating($rating)
    {
        if (is_null($rating)) {
            throw new \InvalidArgumentException('non-nullable rating cannot be null');
        }
        $this->container['rating'] = $rating;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


