<?php
/**
 * UserStatsResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NoScope API
 *
 * Publicly available API for the NoScope platform. Requires authentication for all endpoints. Get your API key from the NoScope dashboard. API Rate Limiting applies to all endpoints and are currently capped at 100 requests per hour. Request api access at <a href='https://CSSkill.com/api'>https://CSSkill.com/api</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@CSSkill.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * UserStatsResponse Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UserStatsResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UserStatsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'matches_played' => 'int',
        'wins' => 'int',
        'losses' => 'int',
        'ties' => 'int',
        'win_rate' => 'float',
        'total_kills' => 'int',
        'total_deaths' => 'int',
        'total_assists' => 'int',
        'total_headshots' => 'int',
        'total_damage' => 'int',
        'total_mvps' => 'int',
        'avg_kills_per_match' => 'float',
        'avg_deaths_per_match' => 'float',
        'avg_assists_per_match' => 'float',
        'avg_headshots_per_match' => 'float',
        'avg_kills_per_round' => 'float',
        'avg_deaths_per_round' => 'float',
        'kd_ratio' => 'float',
        'kast_percentage' => 'float',
        'adr' => 'float',
        'hs_percentage' => 'float',
        'avg_hltv_rating' => 'float',
        'avg_hltv_rating_3' => 'float',
        'avg_rating' => 'float',
        'avg_personal_performance' => 'float',
        'rating_trend' => 'float',
        'avg_aim_score' => 'float',
        'avg_utility_score' => 'float',
        'avg_positioning_score' => 'float',
        'clutch_attempts' => 'int',
        'clutch_wins' => 'int',
        'clutch_win_rate' => 'float',
        'clutch_1v1_attempts' => 'int',
        'clutch_1v1_wins' => 'int',
        'clutch_1v2_wins' => 'int',
        'clutch_1v3_wins' => 'int',
        'total_2k_rounds' => 'IntematchDetailServiceger',
        'total_3k_rounds' => 'int',
        'total_4k_rounds' => 'int',
        'total_5k_rounds' => 'int',
        'total_aces' => 'int',
        'opening_kills' => 'int',
        'opening_deaths' => 'int',
        'opening_duel_success_rate' => 'float',
        'trade_kills' => 'int',
        'trade_opportunities' => 'int',
        'trade_success_rate' => 'float',
        'total_flashes' => 'int',
        'total_smokes' => 'int',
        'total_he_grenades' => 'int',
        'total_molotovs' => 'int',
        'total_enemies_flashed' => 'int',
        'avg_utility_score_value' => 'float',
        'avg_equipment_value' => 'float',
        'rounds_as_t' => 'int',
        'rounds_as_ct' => 'int',
        't_side_win_rate' => 'float',
        'ct_side_win_rate' => 'float',
        't_side_kd' => 'float',
        'ct_side_kd' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'matches_played' => null,
        'wins' => null,
        'losses' => null,
        'ties' => null,
        'win_rate' => 'float',
        'total_kills' => null,
        'total_deaths' => null,
        'total_assists' => null,
        'total_headshots' => null,
        'total_damage' => null,
        'total_mvps' => null,
        'avg_kills_per_match' => 'float',
        'avg_deaths_per_match' => 'float',
        'avg_assists_per_match' => 'float',
        'avg_headshots_per_match' => 'float',
        'avg_kills_per_round' => 'float',
        'avg_deaths_per_round' => 'float',
        'kd_ratio' => 'float',
        'kast_percentage' => 'float',
        'adr' => 'float',
        'hs_percentage' => 'float',
        'avg_hltv_rating' => 'float',
        'avg_hltv_rating_3' => 'float',
        'avg_rating' => 'float',
        'avg_personal_performance' => 'float',
        'rating_trend' => 'float',
        'avg_aim_score' => 'float',
        'avg_utility_score' => 'float',
        'avg_positioning_score' => 'float',
        'clutch_attempts' => null,
        'clutch_wins' => null,
        'clutch_win_rate' => 'float',
        'clutch_1v1_attempts' => null,
        'clutch_1v1_wins' => null,
        'clutch_1v2_wins' => null,
        'clutch_1v3_wins' => null,
        'total_2k_rounds' => null,
        'total_3k_rounds' => null,
        'total_4k_rounds' => null,
        'total_5k_rounds' => null,
        'total_aces' => null,
        'opening_kills' => null,
        'opening_deaths' => null,
        'opening_duel_success_rate' => 'float',
        'trade_kills' => null,
        'trade_opportunities' => null,
        'trade_success_rate' => 'float',
        'total_flashes' => null,
        'total_smokes' => null,
        'total_he_grenades' => null,
        'total_molotovs' => null,
        'total_enemies_flashed' => null,
        'avg_utility_score_value' => 'float',
        'avg_equipment_value' => 'float',
        'rounds_as_t' => null,
        'rounds_as_ct' => null,
        't_side_win_rate' => 'float',
        'ct_side_win_rate' => 'float',
        't_side_kd' => 'float',
        'ct_side_kd' => 'float'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'matches_played' => false,
        'wins' => false,
        'losses' => false,
        'ties' => false,
        'win_rate' => false,
        'total_kills' => false,
        'total_deaths' => false,
        'total_assists' => false,
        'total_headshots' => false,
        'total_damage' => false,
        'total_mvps' => false,
        'avg_kills_per_match' => false,
        'avg_deaths_per_match' => false,
        'avg_assists_per_match' => false,
        'avg_headshots_per_match' => false,
        'avg_kills_per_round' => false,
        'avg_deaths_per_round' => false,
        'kd_ratio' => false,
        'kast_percentage' => false,
        'adr' => false,
        'hs_percentage' => false,
        'avg_hltv_rating' => false,
        'avg_hltv_rating_3' => false,
        'avg_rating' => false,
        'avg_personal_performance' => false,
        'rating_trend' => false,
        'avg_aim_score' => false,
        'avg_utility_score' => false,
        'avg_positioning_score' => false,
        'clutch_attempts' => false,
        'clutch_wins' => false,
        'clutch_win_rate' => false,
        'clutch_1v1_attempts' => false,
        'clutch_1v1_wins' => false,
        'clutch_1v2_wins' => false,
        'clutch_1v3_wins' => false,
        'total_2k_rounds' => false,
        'total_3k_rounds' => false,
        'total_4k_rounds' => false,
        'total_5k_rounds' => false,
        'total_aces' => false,
        'opening_kills' => false,
        'opening_deaths' => false,
        'opening_duel_success_rate' => false,
        'trade_kills' => false,
        'trade_opportunities' => false,
        'trade_success_rate' => false,
        'total_flashes' => false,
        'total_smokes' => false,
        'total_he_grenades' => false,
        'total_molotovs' => false,
        'total_enemies_flashed' => false,
        'avg_utility_score_value' => false,
        'avg_equipment_value' => false,
        'rounds_as_t' => false,
        'rounds_as_ct' => false,
        't_side_win_rate' => false,
        'ct_side_win_rate' => false,
        't_side_kd' => false,
        'ct_side_kd' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'matches_played' => 'matches_played',
        'wins' => 'wins',
        'losses' => 'losses',
        'ties' => 'ties',
        'win_rate' => 'win_rate',
        'total_kills' => 'total_kills',
        'total_deaths' => 'total_deaths',
        'total_assists' => 'total_assists',
        'total_headshots' => 'total_headshots',
        'total_damage' => 'total_damage',
        'total_mvps' => 'total_mvps',
        'avg_kills_per_match' => 'avg_kills_per_match',
        'avg_deaths_per_match' => 'avg_deaths_per_match',
        'avg_assists_per_match' => 'avg_assists_per_match',
        'avg_headshots_per_match' => 'avg_headshots_per_match',
        'avg_kills_per_round' => 'avg_kills_per_round',
        'avg_deaths_per_round' => 'avg_deaths_per_round',
        'kd_ratio' => 'kd_ratio',
        'kast_percentage' => 'kast_percentage',
        'adr' => 'adr',
        'hs_percentage' => 'hs_percentage',
        'avg_hltv_rating' => 'avg_hltv_rating',
        'avg_hltv_rating_3' => 'avg_hltv_rating_3',
        'avg_rating' => 'avg_rating',
        'avg_personal_performance' => 'avg_personal_performance',
        'rating_trend' => 'rating_trend',
        'avg_aim_score' => 'avg_aim_score',
        'avg_utility_score' => 'avg_utility_score',
        'avg_positioning_score' => 'avg_positioning_score',
        'clutch_attempts' => 'clutch_attempts',
        'clutch_wins' => 'clutch_wins',
        'clutch_win_rate' => 'clutch_win_rate',
        'clutch_1v1_attempts' => 'clutch_1v1_attempts',
        'clutch_1v1_wins' => 'clutch_1v1_wins',
        'clutch_1v2_wins' => 'clutch_1v2_wins',
        'clutch_1v3_wins' => 'clutch_1v3_wins',
        'total_2k_rounds' => 'total_2k_rounds',
        'total_3k_rounds' => 'total_3k_rounds',
        'total_4k_rounds' => 'total_4k_rounds',
        'total_5k_rounds' => 'total_5k_rounds',
        'total_aces' => 'total_aces',
        'opening_kills' => 'opening_kills',
        'opening_deaths' => 'opening_deaths',
        'opening_duel_success_rate' => 'opening_duel_success_rate',
        'trade_kills' => 'trade_kills',
        'trade_opportunities' => 'trade_opportunities',
        'trade_success_rate' => 'trade_success_rate',
        'total_flashes' => 'total_flashes',
        'total_smokes' => 'total_smokes',
        'total_he_grenades' => 'total_he_grenades',
        'total_molotovs' => 'total_molotovs',
        'total_enemies_flashed' => 'total_enemies_flashed',
        'avg_utility_score_value' => 'avg_utility_score_value',
        'avg_equipment_value' => 'avg_equipment_value',
        'rounds_as_t' => 'rounds_as_t',
        'rounds_as_ct' => 'rounds_as_ct',
        't_side_win_rate' => 't_side_win_rate',
        'ct_side_win_rate' => 'ct_side_win_rate',
        't_side_kd' => 't_side_kd',
        'ct_side_kd' => 'ct_side_kd'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'matches_played' => 'setMatchesPlayed',
        'wins' => 'setWins',
        'losses' => 'setLosses',
        'ties' => 'setTies',
        'win_rate' => 'setWinRate',
        'total_kills' => 'setTotalKills',
        'total_deaths' => 'setTotalDeaths',
        'total_assists' => 'setTotalAssists',
        'total_headshots' => 'setTotalHeadshots',
        'total_damage' => 'setTotalDamage',
        'total_mvps' => 'setTotalMvps',
        'avg_kills_per_match' => 'setAvgKillsPerMatch',
        'avg_deaths_per_match' => 'setAvgDeathsPerMatch',
        'avg_assists_per_match' => 'setAvgAssistsPerMatch',
        'avg_headshots_per_match' => 'setAvgHeadshotsPerMatch',
        'avg_kills_per_round' => 'setAvgKillsPerRound',
        'avg_deaths_per_round' => 'setAvgDeathsPerRound',
        'kd_ratio' => 'setKdRatio',
        'kast_percentage' => 'setKastPercentage',
        'adr' => 'setAdr',
        'hs_percentage' => 'setHsPercentage',
        'avg_hltv_rating' => 'setAvgHltvRating',
        'avg_hltv_rating_3' => 'setAvgHltvRating3',
        'avg_rating' => 'setAvgRating',
        'avg_personal_performance' => 'setAvgPersonalPerformance',
        'rating_trend' => 'setRatingTrend',
        'avg_aim_score' => 'setAvgAimScore',
        'avg_utility_score' => 'setAvgUtilityScore',
        'avg_positioning_score' => 'setAvgPositioningScore',
        'clutch_attempts' => 'setClutchAttempts',
        'clutch_wins' => 'setClutchWins',
        'clutch_win_rate' => 'setClutchWinRate',
        'clutch_1v1_attempts' => 'setClutch1v1Attempts',
        'clutch_1v1_wins' => 'setClutch1v1Wins',
        'clutch_1v2_wins' => 'setClutch1v2Wins',
        'clutch_1v3_wins' => 'setClutch1v3Wins',
        'total_2k_rounds' => 'setTotal2kRounds',
        'total_3k_rounds' => 'setTotal3kRounds',
        'total_4k_rounds' => 'setTotal4kRounds',
        'total_5k_rounds' => 'setTotal5kRounds',
        'total_aces' => 'setTotalAces',
        'opening_kills' => 'setOpeningKills',
        'opening_deaths' => 'setOpeningDeaths',
        'opening_duel_success_rate' => 'setOpeningDuelSuccessRate',
        'trade_kills' => 'setTradeKills',
        'trade_opportunities' => 'setTradeOpportunities',
        'trade_success_rate' => 'setTradeSuccessRate',
        'total_flashes' => 'setTotalFlashes',
        'total_smokes' => 'setTotalSmokes',
        'total_he_grenades' => 'setTotalHeGrenades',
        'total_molotovs' => 'setTotalMolotovs',
        'total_enemies_flashed' => 'setTotalEnemiesFlashed',
        'avg_utility_score_value' => 'setAvgUtilityScoreValue',
        'avg_equipment_value' => 'setAvgEquipmentValue',
        'rounds_as_t' => 'setRoundsAsT',
        'rounds_as_ct' => 'setRoundsAsCt',
        't_side_win_rate' => 'setTSideWinRate',
        'ct_side_win_rate' => 'setCtSideWinRate',
        't_side_kd' => 'setTSideKd',
        'ct_side_kd' => 'setCtSideKd'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'matches_played' => 'getMatchesPlayed',
        'wins' => 'getWins',
        'losses' => 'getLosses',
        'ties' => 'getTies',
        'win_rate' => 'getWinRate',
        'total_kills' => 'getTotalKills',
        'total_deaths' => 'getTotalDeaths',
        'total_assists' => 'getTotalAssists',
        'total_headshots' => 'getTotalHeadshots',
        'total_damage' => 'getTotalDamage',
        'total_mvps' => 'getTotalMvps',
        'avg_kills_per_match' => 'getAvgKillsPerMatch',
        'avg_deaths_per_match' => 'getAvgDeathsPerMatch',
        'avg_assists_per_match' => 'getAvgAssistsPerMatch',
        'avg_headshots_per_match' => 'getAvgHeadshotsPerMatch',
        'avg_kills_per_round' => 'getAvgKillsPerRound',
        'avg_deaths_per_round' => 'getAvgDeathsPerRound',
        'kd_ratio' => 'getKdRatio',
        'kast_percentage' => 'getKastPercentage',
        'adr' => 'getAdr',
        'hs_percentage' => 'getHsPercentage',
        'avg_hltv_rating' => 'getAvgHltvRating',
        'avg_hltv_rating_3' => 'getAvgHltvRating3',
        'avg_rating' => 'getAvgRating',
        'avg_personal_performance' => 'getAvgPersonalPerformance',
        'rating_trend' => 'getRatingTrend',
        'avg_aim_score' => 'getAvgAimScore',
        'avg_utility_score' => 'getAvgUtilityScore',
        'avg_positioning_score' => 'getAvgPositioningScore',
        'clutch_attempts' => 'getClutchAttempts',
        'clutch_wins' => 'getClutchWins',
        'clutch_win_rate' => 'getClutchWinRate',
        'clutch_1v1_attempts' => 'getClutch1v1Attempts',
        'clutch_1v1_wins' => 'getClutch1v1Wins',
        'clutch_1v2_wins' => 'getClutch1v2Wins',
        'clutch_1v3_wins' => 'getClutch1v3Wins',
        'total_2k_rounds' => 'getTotal2kRounds',
        'total_3k_rounds' => 'getTotal3kRounds',
        'total_4k_rounds' => 'getTotal4kRounds',
        'total_5k_rounds' => 'getTotal5kRounds',
        'total_aces' => 'getTotalAces',
        'opening_kills' => 'getOpeningKills',
        'opening_deaths' => 'getOpeningDeaths',
        'opening_duel_success_rate' => 'getOpeningDuelSuccessRate',
        'trade_kills' => 'getTradeKills',
        'trade_opportunities' => 'getTradeOpportunities',
        'trade_success_rate' => 'getTradeSuccessRate',
        'total_flashes' => 'getTotalFlashes',
        'total_smokes' => 'getTotalSmokes',
        'total_he_grenades' => 'getTotalHeGrenades',
        'total_molotovs' => 'getTotalMolotovs',
        'total_enemies_flashed' => 'getTotalEnemiesFlashed',
        'avg_utility_score_value' => 'getAvgUtilityScoreValue',
        'avg_equipment_value' => 'getAvgEquipmentValue',
        'rounds_as_t' => 'getRoundsAsT',
        'rounds_as_ct' => 'getRoundsAsCt',
        't_side_win_rate' => 'getTSideWinRate',
        'ct_side_win_rate' => 'getCtSideWinRate',
        't_side_kd' => 'getTSideKd',
        'ct_side_kd' => 'getCtSideKd'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('matches_played', $data ?? [], null);
        $this->setIfExists('wins', $data ?? [], null);
        $this->setIfExists('losses', $data ?? [], null);
        $this->setIfExists('ties', $data ?? [], null);
        $this->setIfExists('win_rate', $data ?? [], null);
        $this->setIfExists('total_kills', $data ?? [], null);
        $this->setIfExists('total_deaths', $data ?? [], null);
        $this->setIfExists('total_assists', $data ?? [], null);
        $this->setIfExists('total_headshots', $data ?? [], null);
        $this->setIfExists('total_damage', $data ?? [], null);
        $this->setIfExists('total_mvps', $data ?? [], null);
        $this->setIfExists('avg_kills_per_match', $data ?? [], null);
        $this->setIfExists('avg_deaths_per_match', $data ?? [], null);
        $this->setIfExists('avg_assists_per_match', $data ?? [], null);
        $this->setIfExists('avg_headshots_per_match', $data ?? [], null);
        $this->setIfExists('avg_kills_per_round', $data ?? [], null);
        $this->setIfExists('avg_deaths_per_round', $data ?? [], null);
        $this->setIfExists('kd_ratio', $data ?? [], null);
        $this->setIfExists('kast_percentage', $data ?? [], null);
        $this->setIfExists('adr', $data ?? [], null);
        $this->setIfExists('hs_percentage', $data ?? [], null);
        $this->setIfExists('avg_hltv_rating', $data ?? [], null);
        $this->setIfExists('avg_hltv_rating_3', $data ?? [], null);
        $this->setIfExists('avg_rating', $data ?? [], null);
        $this->setIfExists('avg_personal_performance', $data ?? [], null);
        $this->setIfExists('rating_trend', $data ?? [], null);
        $this->setIfExists('avg_aim_score', $data ?? [], null);
        $this->setIfExists('avg_utility_score', $data ?? [], null);
        $this->setIfExists('avg_positioning_score', $data ?? [], null);
        $this->setIfExists('clutch_attempts', $data ?? [], null);
        $this->setIfExists('clutch_wins', $data ?? [], null);
        $this->setIfExists('clutch_win_rate', $data ?? [], null);
        $this->setIfExists('clutch_1v1_attempts', $data ?? [], null);
        $this->setIfExists('clutch_1v1_wins', $data ?? [], null);
        $this->setIfExists('clutch_1v2_wins', $data ?? [], null);
        $this->setIfExists('clutch_1v3_wins', $data ?? [], null);
        $this->setIfExists('total_2k_rounds', $data ?? [], null);
        $this->setIfExists('total_3k_rounds', $data ?? [], null);
        $this->setIfExists('total_4k_rounds', $data ?? [], null);
        $this->setIfExists('total_5k_rounds', $data ?? [], null);
        $this->setIfExists('total_aces', $data ?? [], null);
        $this->setIfExists('opening_kills', $data ?? [], null);
        $this->setIfExists('opening_deaths', $data ?? [], null);
        $this->setIfExists('opening_duel_success_rate', $data ?? [], null);
        $this->setIfExists('trade_kills', $data ?? [], null);
        $this->setIfExists('trade_opportunities', $data ?? [], null);
        $this->setIfExists('trade_success_rate', $data ?? [], null);
        $this->setIfExists('total_flashes', $data ?? [], null);
        $this->setIfExists('total_smokes', $data ?? [], null);
        $this->setIfExists('total_he_grenades', $data ?? [], null);
        $this->setIfExists('total_molotovs', $data ?? [], null);
        $this->setIfExists('total_enemies_flashed', $data ?? [], null);
        $this->setIfExists('avg_utility_score_value', $data ?? [], null);
        $this->setIfExists('avg_equipment_value', $data ?? [], null);
        $this->setIfExists('rounds_as_t', $data ?? [], null);
        $this->setIfExists('rounds_as_ct', $data ?? [], null);
        $this->setIfExists('t_side_win_rate', $data ?? [], null);
        $this->setIfExists('ct_side_win_rate', $data ?? [], null);
        $this->setIfExists('t_side_kd', $data ?? [], null);
        $this->setIfExists('ct_side_kd', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets matches_played
     *
     * @return int|null
     */
    public function getMatchesPlayed()
    {
        return $this->container['matches_played'];
    }

    /**
     * Sets matches_played
     *
     * @param int|null $matches_played matches_played
     *
     * @return self
     */
    public function setMatchesPlayed($matches_played)
    {
        if (is_null($matches_played)) {
            throw new \InvalidArgumentException('non-nullable matches_played cannot be null');
        }
        $this->container['matches_played'] = $matches_played;

        return $this;
    }

    /**
     * Gets wins
     *
     * @return int|null
     */
    public function getWins()
    {
        return $this->container['wins'];
    }

    /**
     * Sets wins
     *
     * @param int|null $wins wins
     *
     * @return self
     */
    public function setWins($wins)
    {
        if (is_null($wins)) {
            throw new \InvalidArgumentException('non-nullable wins cannot be null');
        }
        $this->container['wins'] = $wins;

        return $this;
    }

    /**
     * Gets losses
     *
     * @return int|null
     */
    public function getLosses()
    {
        return $this->container['losses'];
    }

    /**
     * Sets losses
     *
     * @param int|null $losses losses
     *
     * @return self
     */
    public function setLosses($losses)
    {
        if (is_null($losses)) {
            throw new \InvalidArgumentException('non-nullable losses cannot be null');
        }
        $this->container['losses'] = $losses;

        return $this;
    }

    /**
     * Gets ties
     *
     * @return int|null
     */
    public function getTies()
    {
        return $this->container['ties'];
    }

    /**
     * Sets ties
     *
     * @param int|null $ties ties
     *
     * @return self
     */
    public function setTies($ties)
    {
        if (is_null($ties)) {
            throw new \InvalidArgumentException('non-nullable ties cannot be null');
        }
        $this->container['ties'] = $ties;

        return $this;
    }

    /**
     * Gets win_rate
     *
     * @return float|null
     */
    public function getWinRate()
    {
        return $this->container['win_rate'];
    }

    /**
     * Sets win_rate
     *
     * @param float|null $win_rate win_rate
     *
     * @return self
     */
    public function setWinRate($win_rate)
    {
        if (is_null($win_rate)) {
            throw new \InvalidArgumentException('non-nullable win_rate cannot be null');
        }
        $this->container['win_rate'] = $win_rate;

        return $this;
    }

    /**
     * Gets total_kills
     *
     * @return int|null
     */
    public function getTotalKills()
    {
        return $this->container['total_kills'];
    }

    /**
     * Sets total_kills
     *
     * @param int|null $total_kills total_kills
     *
     * @return self
     */
    public function setTotalKills($total_kills)
    {
        if (is_null($total_kills)) {
            throw new \InvalidArgumentException('non-nullable total_kills cannot be null');
        }
        $this->container['total_kills'] = $total_kills;

        return $this;
    }

    /**
     * Gets total_deaths
     *
     * @return int|null
     */
    public function getTotalDeaths()
    {
        return $this->container['total_deaths'];
    }

    /**
     * Sets total_deaths
     *
     * @param int|null $total_deaths total_deaths
     *
     * @return self
     */
    public function setTotalDeaths($total_deaths)
    {
        if (is_null($total_deaths)) {
            throw new \InvalidArgumentException('non-nullable total_deaths cannot be null');
        }
        $this->container['total_deaths'] = $total_deaths;

        return $this;
    }

    /**
     * Gets total_assists
     *
     * @return int|null
     */
    public function getTotalAssists()
    {
        return $this->container['total_assists'];
    }

    /**
     * Sets total_assists
     *
     * @param int|null $total_assists total_assists
     *
     * @return self
     */
    public function setTotalAssists($total_assists)
    {
        if (is_null($total_assists)) {
            throw new \InvalidArgumentException('non-nullable total_assists cannot be null');
        }
        $this->container['total_assists'] = $total_assists;

        return $this;
    }

    /**
     * Gets total_headshots
     *
     * @return int|null
     */
    public function getTotalHeadshots()
    {
        return $this->container['total_headshots'];
    }

    /**
     * Sets total_headshots
     *
     * @param int|null $total_headshots total_headshots
     *
     * @return self
     */
    public function setTotalHeadshots($total_headshots)
    {
        if (is_null($total_headshots)) {
            throw new \InvalidArgumentException('non-nullable total_headshots cannot be null');
        }
        $this->container['total_headshots'] = $total_headshots;

        return $this;
    }

    /**
     * Gets total_damage
     *
     * @return int|null
     */
    public function getTotalDamage()
    {
        return $this->container['total_damage'];
    }

    /**
     * Sets total_damage
     *
     * @param int|null $total_damage total_damage
     *
     * @return self
     */
    public function setTotalDamage($total_damage)
    {
        if (is_null($total_damage)) {
            throw new \InvalidArgumentException('non-nullable total_damage cannot be null');
        }
        $this->container['total_damage'] = $total_damage;

        return $this;
    }

    /**
     * Gets total_mvps
     *
     * @return int|null
     */
    public function getTotalMvps()
    {
        return $this->container['total_mvps'];
    }

    /**
     * Sets total_mvps
     *
     * @param int|null $total_mvps total_mvps
     *
     * @return self
     */
    public function setTotalMvps($total_mvps)
    {
        if (is_null($total_mvps)) {
            throw new \InvalidArgumentException('non-nullable total_mvps cannot be null');
        }
        $this->container['total_mvps'] = $total_mvps;

        return $this;
    }

    /**
     * Gets avg_kills_per_match
     *
     * @return float|null
     */
    public function getAvgKillsPerMatch()
    {
        return $this->container['avg_kills_per_match'];
    }

    /**
     * Sets avg_kills_per_match
     *
     * @param float|null $avg_kills_per_match avg_kills_per_match
     *
     * @return self
     */
    public function setAvgKillsPerMatch($avg_kills_per_match)
    {
        if (is_null($avg_kills_per_match)) {
            throw new \InvalidArgumentException('non-nullable avg_kills_per_match cannot be null');
        }
        $this->container['avg_kills_per_match'] = $avg_kills_per_match;

        return $this;
    }

    /**
     * Gets avg_deaths_per_match
     *
     * @return float|null
     */
    public function getAvgDeathsPerMatch()
    {
        return $this->container['avg_deaths_per_match'];
    }

    /**
     * Sets avg_deaths_per_match
     *
     * @param float|null $avg_deaths_per_match avg_deaths_per_match
     *
     * @return self
     */
    public function setAvgDeathsPerMatch($avg_deaths_per_match)
    {
        if (is_null($avg_deaths_per_match)) {
            throw new \InvalidArgumentException('non-nullable avg_deaths_per_match cannot be null');
        }
        $this->container['avg_deaths_per_match'] = $avg_deaths_per_match;

        return $this;
    }

    /**
     * Gets avg_assists_per_match
     *
     * @return float|null
     */
    public function getAvgAssistsPerMatch()
    {
        return $this->container['avg_assists_per_match'];
    }

    /**
     * Sets avg_assists_per_match
     *
     * @param float|null $avg_assists_per_match avg_assists_per_match
     *
     * @return self
     */
    public function setAvgAssistsPerMatch($avg_assists_per_match)
    {
        if (is_null($avg_assists_per_match)) {
            throw new \InvalidArgumentException('non-nullable avg_assists_per_match cannot be null');
        }
        $this->container['avg_assists_per_match'] = $avg_assists_per_match;

        return $this;
    }

    /**
     * Gets avg_headshots_per_match
     *
     * @return float|null
     */
    public function getAvgHeadshotsPerMatch()
    {
        return $this->container['avg_headshots_per_match'];
    }

    /**
     * Sets avg_headshots_per_match
     *
     * @param float|null $avg_headshots_per_match avg_headshots_per_match
     *
     * @return self
     */
    public function setAvgHeadshotsPerMatch($avg_headshots_per_match)
    {
        if (is_null($avg_headshots_per_match)) {
            throw new \InvalidArgumentException('non-nullable avg_headshots_per_match cannot be null');
        }
        $this->container['avg_headshots_per_match'] = $avg_headshots_per_match;

        return $this;
    }

    /**
     * Gets avg_kills_per_round
     *
     * @return float|null
     */
    public function getAvgKillsPerRound()
    {
        return $this->container['avg_kills_per_round'];
    }

    /**
     * Sets avg_kills_per_round
     *
     * @param float|null $avg_kills_per_round avg_kills_per_round
     *
     * @return self
     */
    public function setAvgKillsPerRound($avg_kills_per_round)
    {
        if (is_null($avg_kills_per_round)) {
            throw new \InvalidArgumentException('non-nullable avg_kills_per_round cannot be null');
        }
        $this->container['avg_kills_per_round'] = $avg_kills_per_round;

        return $this;
    }

    /**
     * Gets avg_deaths_per_round
     *
     * @return float|null
     */
    public function getAvgDeathsPerRound()
    {
        return $this->container['avg_deaths_per_round'];
    }

    /**
     * Sets avg_deaths_per_round
     *
     * @param float|null $avg_deaths_per_round avg_deaths_per_round
     *
     * @return self
     */
    public function setAvgDeathsPerRound($avg_deaths_per_round)
    {
        if (is_null($avg_deaths_per_round)) {
            throw new \InvalidArgumentException('non-nullable avg_deaths_per_round cannot be null');
        }
        $this->container['avg_deaths_per_round'] = $avg_deaths_per_round;

        return $this;
    }

    /**
     * Gets kd_ratio
     *
     * @return float|null
     */
    public function getKdRatio()
    {
        return $this->container['kd_ratio'];
    }

    /**
     * Sets kd_ratio
     *
     * @param float|null $kd_ratio kd_ratio
     *
     * @return self
     */
    public function setKdRatio($kd_ratio)
    {
        if (is_null($kd_ratio)) {
            throw new \InvalidArgumentException('non-nullable kd_ratio cannot be null');
        }
        $this->container['kd_ratio'] = $kd_ratio;

        return $this;
    }

    /**
     * Gets kast_percentage
     *
     * @return float|null
     */
    public function getKastPercentage()
    {
        return $this->container['kast_percentage'];
    }

    /**
     * Sets kast_percentage
     *
     * @param float|null $kast_percentage kast_percentage
     *
     * @return self
     */
    public function setKastPercentage($kast_percentage)
    {
        if (is_null($kast_percentage)) {
            throw new \InvalidArgumentException('non-nullable kast_percentage cannot be null');
        }
        $this->container['kast_percentage'] = $kast_percentage;

        return $this;
    }

    /**
     * Gets adr
     *
     * @return float|null
     */
    public function getAdr()
    {
        return $this->container['adr'];
    }

    /**
     * Sets adr
     *
     * @param float|null $adr adr
     *
     * @return self
     */
    public function setAdr($adr)
    {
        if (is_null($adr)) {
            throw new \InvalidArgumentException('non-nullable adr cannot be null');
        }
        $this->container['adr'] = $adr;

        return $this;
    }

    /**
     * Gets hs_percentage
     *
     * @return float|null
     */
    public function getHsPercentage()
    {
        return $this->container['hs_percentage'];
    }

    /**
     * Sets hs_percentage
     *
     * @param float|null $hs_percentage hs_percentage
     *
     * @return self
     */
    public function setHsPercentage($hs_percentage)
    {
        if (is_null($hs_percentage)) {
            throw new \InvalidArgumentException('non-nullable hs_percentage cannot be null');
        }
        $this->container['hs_percentage'] = $hs_percentage;

        return $this;
    }

    /**
     * Gets avg_hltv_rating
     *
     * @return float|null
     */
    public function getAvgHltvRating()
    {
        return $this->container['avg_hltv_rating'];
    }

    /**
     * Sets avg_hltv_rating
     *
     * @param float|null $avg_hltv_rating avg_hltv_rating
     *
     * @return self
     */
    public function setAvgHltvRating($avg_hltv_rating)
    {
        if (is_null($avg_hltv_rating)) {
            throw new \InvalidArgumentException('non-nullable avg_hltv_rating cannot be null');
        }
        $this->container['avg_hltv_rating'] = $avg_hltv_rating;

        return $this;
    }

    /**
     * Gets avg_hltv_rating_3
     *
     * @return float|null
     */
    public function getAvgHltvRating3()
    {
        return $this->container['avg_hltv_rating_3'];
    }

    /**
     * Sets avg_hltv_rating_3
     *
     * @param float|null $avg_hltv_rating_3 avg_hltv_rating_3
     *
     * @return self
     */
    public function setAvgHltvRating3($avg_hltv_rating_3)
    {
        if (is_null($avg_hltv_rating_3)) {
            throw new \InvalidArgumentException('non-nullable avg_hltv_rating_3 cannot be null');
        }
        $this->container['avg_hltv_rating_3'] = $avg_hltv_rating_3;

        return $this;
    }

    /**
     * Gets avg_rating
     *
     * @return float|null
     */
    public function getAvgRating()
    {
        return $this->container['avg_rating'];
    }

    /**
     * Sets avg_rating
     *
     * @param float|null $avg_rating avg_rating
     *
     * @return self
     */
    public function setAvgRating($avg_rating)
    {
        if (is_null($avg_rating)) {
            throw new \InvalidArgumentException('non-nullable avg_rating cannot be null');
        }
        $this->container['avg_rating'] = $avg_rating;

        return $this;
    }

    /**
     * Gets avg_personal_performance
     *
     * @return float|null
     */
    public function getAvgPersonalPerformance()
    {
        return $this->container['avg_personal_performance'];
    }

    /**
     * Sets avg_personal_performance
     *
     * @param float|null $avg_personal_performance avg_personal_performance
     *
     * @return self
     */
    public function setAvgPersonalPerformance($avg_personal_performance)
    {
        if (is_null($avg_personal_performance)) {
            throw new \InvalidArgumentException('non-nullable avg_personal_performance cannot be null');
        }
        $this->container['avg_personal_performance'] = $avg_personal_performance;

        return $this;
    }

    /**
     * Gets rating_trend
     *
     * @return float|null
     */
    public function getRatingTrend()
    {
        return $this->container['rating_trend'];
    }

    /**
     * Sets rating_trend
     *
     * @param float|null $rating_trend rating_trend
     *
     * @return self
     */
    public function setRatingTrend($rating_trend)
    {
        if (is_null($rating_trend)) {
            throw new \InvalidArgumentException('non-nullable rating_trend cannot be null');
        }
        $this->container['rating_trend'] = $rating_trend;

        return $this;
    }

    /**
     * Gets avg_aim_score
     *
     * @return float|null
     */
    public function getAvgAimScore()
    {
        return $this->container['avg_aim_score'];
    }

    /**
     * Sets avg_aim_score
     *
     * @param float|null $avg_aim_score avg_aim_score
     *
     * @return self
     */
    public function setAvgAimScore($avg_aim_score)
    {
        if (is_null($avg_aim_score)) {
            throw new \InvalidArgumentException('non-nullable avg_aim_score cannot be null');
        }
        $this->container['avg_aim_score'] = $avg_aim_score;

        return $this;
    }

    /**
     * Gets avg_utility_score
     *
     * @return float|null
     */
    public function getAvgUtilityScore()
    {
        return $this->container['avg_utility_score'];
    }

    /**
     * Sets avg_utility_score
     *
     * @param float|null $avg_utility_score avg_utility_score
     *
     * @return self
     */
    public function setAvgUtilityScore($avg_utility_score)
    {
        if (is_null($avg_utility_score)) {
            throw new \InvalidArgumentException('non-nullable avg_utility_score cannot be null');
        }
        $this->container['avg_utility_score'] = $avg_utility_score;

        return $this;
    }

    /**
     * Gets avg_positioning_score
     *
     * @return float|null
     */
    public function getAvgPositioningScore()
    {
        return $this->container['avg_positioning_score'];
    }

    /**
     * Sets avg_positioning_score
     *
     * @param float|null $avg_positioning_score avg_positioning_score
     *
     * @return self
     */
    public function setAvgPositioningScore($avg_positioning_score)
    {
        if (is_null($avg_positioning_score)) {
            throw new \InvalidArgumentException('non-nullable avg_positioning_score cannot be null');
        }
        $this->container['avg_positioning_score'] = $avg_positioning_score;

        return $this;
    }

    /**
     * Gets clutch_attempts
     *
     * @return int|null
     */
    public function getClutchAttempts()
    {
        return $this->container['clutch_attempts'];
    }

    /**
     * Sets clutch_attempts
     *
     * @param int|null $clutch_attempts clutch_attempts
     *
     * @return self
     */
    public function setClutchAttempts($clutch_attempts)
    {
        if (is_null($clutch_attempts)) {
            throw new \InvalidArgumentException('non-nullable clutch_attempts cannot be null');
        }
        $this->container['clutch_attempts'] = $clutch_attempts;

        return $this;
    }

    /**
     * Gets clutch_wins
     *
     * @return int|null
     */
    public function getClutchWins()
    {
        return $this->container['clutch_wins'];
    }

    /**
     * Sets clutch_wins
     *
     * @param int|null $clutch_wins clutch_wins
     *
     * @return self
     */
    public function setClutchWins($clutch_wins)
    {
        if (is_null($clutch_wins)) {
            throw new \InvalidArgumentException('non-nullable clutch_wins cannot be null');
        }
        $this->container['clutch_wins'] = $clutch_wins;

        return $this;
    }

    /**
     * Gets clutch_win_rate
     *
     * @return float|null
     */
    public function getClutchWinRate()
    {
        return $this->container['clutch_win_rate'];
    }

    /**
     * Sets clutch_win_rate
     *
     * @param float|null $clutch_win_rate clutch_win_rate
     *
     * @return self
     */
    public function setClutchWinRate($clutch_win_rate)
    {
        if (is_null($clutch_win_rate)) {
            throw new \InvalidArgumentException('non-nullable clutch_win_rate cannot be null');
        }
        $this->container['clutch_win_rate'] = $clutch_win_rate;

        return $this;
    }

    /**
     * Gets clutch_1v1_attempts
     *
     * @return int|null
     */
    public function getClutch1v1Attempts()
    {
        return $this->container['clutch_1v1_attempts'];
    }

    /**
     * Sets clutch_1v1_attempts
     *
     * @param int|null $clutch_1v1_attempts clutch_1v1_attempts
     *
     * @return self
     */
    public function setClutch1v1Attempts($clutch_1v1_attempts)
    {
        if (is_null($clutch_1v1_attempts)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v1_attempts cannot be null');
        }
        $this->container['clutch_1v1_attempts'] = $clutch_1v1_attempts;

        return $this;
    }

    /**
     * Gets clutch_1v1_wins
     *
     * @return int|null
     */
    public function getClutch1v1Wins()
    {
        return $this->container['clutch_1v1_wins'];
    }

    /**
     * Sets clutch_1v1_wins
     *
     * @param int|null $clutch_1v1_wins clutch_1v1_wins
     *
     * @return self
     */
    public function setClutch1v1Wins($clutch_1v1_wins)
    {
        if (is_null($clutch_1v1_wins)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v1_wins cannot be null');
        }
        $this->container['clutch_1v1_wins'] = $clutch_1v1_wins;

        return $this;
    }

    /**
     * Gets clutch_1v2_wins
     *
     * @return int|null
     */
    public function getClutch1v2Wins()
    {
        return $this->container['clutch_1v2_wins'];
    }

    /**
     * Sets clutch_1v2_wins
     *
     * @param int|null $clutch_1v2_wins clutch_1v2_wins
     *
     * @return self
     */
    public function setClutch1v2Wins($clutch_1v2_wins)
    {
        if (is_null($clutch_1v2_wins)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v2_wins cannot be null');
        }
        $this->container['clutch_1v2_wins'] = $clutch_1v2_wins;

        return $this;
    }

    /**
     * Gets clutch_1v3_wins
     *
     * @return int|null
     */
    public function getClutch1v3Wins()
    {
        return $this->container['clutch_1v3_wins'];
    }

    /**
     * Sets clutch_1v3_wins
     *
     * @param int|null $clutch_1v3_wins clutch_1v3_wins
     *
     * @return self
     */
    public function setClutch1v3Wins($clutch_1v3_wins)
    {
        if (is_null($clutch_1v3_wins)) {
            throw new \InvalidArgumentException('non-nullable clutch_1v3_wins cannot be null');
        }
        $this->container['clutch_1v3_wins'] = $clutch_1v3_wins;

        return $this;
    }

    /**
     * Gets total_2k_rounds
     *
     * @return IntematchDetailServiceger|null
     */
    public function getTotal2kRounds()
    {
        return $this->container['total_2k_rounds'];
    }

    /**
     * Sets total_2k_rounds
     *
     * @param IntematchDetailServiceger|null $total_2k_rounds total_2k_rounds
     *
     * @return self
     */
    public function setTotal2kRounds($total_2k_rounds)
    {
        if (is_null($total_2k_rounds)) {
            throw new \InvalidArgumentException('non-nullable total_2k_rounds cannot be null');
        }
        $this->container['total_2k_rounds'] = $total_2k_rounds;

        return $this;
    }

    /**
     * Gets total_3k_rounds
     *
     * @return int|null
     */
    public function getTotal3kRounds()
    {
        return $this->container['total_3k_rounds'];
    }

    /**
     * Sets total_3k_rounds
     *
     * @param int|null $total_3k_rounds total_3k_rounds
     *
     * @return self
     */
    public function setTotal3kRounds($total_3k_rounds)
    {
        if (is_null($total_3k_rounds)) {
            throw new \InvalidArgumentException('non-nullable total_3k_rounds cannot be null');
        }
        $this->container['total_3k_rounds'] = $total_3k_rounds;

        return $this;
    }

    /**
     * Gets total_4k_rounds
     *
     * @return int|null
     */
    public function getTotal4kRounds()
    {
        return $this->container['total_4k_rounds'];
    }

    /**
     * Sets total_4k_rounds
     *
     * @param int|null $total_4k_rounds total_4k_rounds
     *
     * @return self
     */
    public function setTotal4kRounds($total_4k_rounds)
    {
        if (is_null($total_4k_rounds)) {
            throw new \InvalidArgumentException('non-nullable total_4k_rounds cannot be null');
        }
        $this->container['total_4k_rounds'] = $total_4k_rounds;

        return $this;
    }

    /**
     * Gets total_5k_rounds
     *
     * @return int|null
     */
    public function getTotal5kRounds()
    {
        return $this->container['total_5k_rounds'];
    }

    /**
     * Sets total_5k_rounds
     *
     * @param int|null $total_5k_rounds total_5k_rounds
     *
     * @return self
     */
    public function setTotal5kRounds($total_5k_rounds)
    {
        if (is_null($total_5k_rounds)) {
            throw new \InvalidArgumentException('non-nullable total_5k_rounds cannot be null');
        }
        $this->container['total_5k_rounds'] = $total_5k_rounds;

        return $this;
    }

    /**
     * Gets total_aces
     *
     * @return int|null
     */
    public function getTotalAces()
    {
        return $this->container['total_aces'];
    }

    /**
     * Sets total_aces
     *
     * @param int|null $total_aces total_aces
     *
     * @return self
     */
    public function setTotalAces($total_aces)
    {
        if (is_null($total_aces)) {
            throw new \InvalidArgumentException('non-nullable total_aces cannot be null');
        }
        $this->container['total_aces'] = $total_aces;

        return $this;
    }

    /**
     * Gets opening_kills
     *
     * @return int|null
     */
    public function getOpeningKills()
    {
        return $this->container['opening_kills'];
    }

    /**
     * Sets opening_kills
     *
     * @param int|null $opening_kills opening_kills
     *
     * @return self
     */
    public function setOpeningKills($opening_kills)
    {
        if (is_null($opening_kills)) {
            throw new \InvalidArgumentException('non-nullable opening_kills cannot be null');
        }
        $this->container['opening_kills'] = $opening_kills;

        return $this;
    }

    /**
     * Gets opening_deaths
     *
     * @return int|null
     */
    public function getOpeningDeaths()
    {
        return $this->container['opening_deaths'];
    }

    /**
     * Sets opening_deaths
     *
     * @param int|null $opening_deaths opening_deaths
     *
     * @return self
     */
    public function setOpeningDeaths($opening_deaths)
    {
        if (is_null($opening_deaths)) {
            throw new \InvalidArgumentException('non-nullable opening_deaths cannot be null');
        }
        $this->container['opening_deaths'] = $opening_deaths;

        return $this;
    }

    /**
     * Gets opening_duel_success_rate
     *
     * @return float|null
     */
    public function getOpeningDuelSuccessRate()
    {
        return $this->container['opening_duel_success_rate'];
    }

    /**
     * Sets opening_duel_success_rate
     *
     * @param float|null $opening_duel_success_rate opening_duel_success_rate
     *
     * @return self
     */
    public function setOpeningDuelSuccessRate($opening_duel_success_rate)
    {
        if (is_null($opening_duel_success_rate)) {
            throw new \InvalidArgumentException('non-nullable opening_duel_success_rate cannot be null');
        }
        $this->container['opening_duel_success_rate'] = $opening_duel_success_rate;

        return $this;
    }

    /**
     * Gets trade_kills
     *
     * @return int|null
     */
    public function getTradeKills()
    {
        return $this->container['trade_kills'];
    }

    /**
     * Sets trade_kills
     *
     * @param int|null $trade_kills trade_kills
     *
     * @return self
     */
    public function setTradeKills($trade_kills)
    {
        if (is_null($trade_kills)) {
            throw new \InvalidArgumentException('non-nullable trade_kills cannot be null');
        }
        $this->container['trade_kills'] = $trade_kills;

        return $this;
    }

    /**
     * Gets trade_opportunities
     *
     * @return int|null
     */
    public function getTradeOpportunities()
    {
        return $this->container['trade_opportunities'];
    }

    /**
     * Sets trade_opportunities
     *
     * @param int|null $trade_opportunities trade_opportunities
     *
     * @return self
     */
    public function setTradeOpportunities($trade_opportunities)
    {
        if (is_null($trade_opportunities)) {
            throw new \InvalidArgumentException('non-nullable trade_opportunities cannot be null');
        }
        $this->container['trade_opportunities'] = $trade_opportunities;

        return $this;
    }

    /**
     * Gets trade_success_rate
     *
     * @return float|null
     */
    public function getTradeSuccessRate()
    {
        return $this->container['trade_success_rate'];
    }

    /**
     * Sets trade_success_rate
     *
     * @param float|null $trade_success_rate trade_success_rate
     *
     * @return self
     */
    public function setTradeSuccessRate($trade_success_rate)
    {
        if (is_null($trade_success_rate)) {
            throw new \InvalidArgumentException('non-nullable trade_success_rate cannot be null');
        }
        $this->container['trade_success_rate'] = $trade_success_rate;

        return $this;
    }

    /**
     * Gets total_flashes
     *
     * @return int|null
     */
    public function getTotalFlashes()
    {
        return $this->container['total_flashes'];
    }

    /**
     * Sets total_flashes
     *
     * @param int|null $total_flashes total_flashes
     *
     * @return self
     */
    public function setTotalFlashes($total_flashes)
    {
        if (is_null($total_flashes)) {
            throw new \InvalidArgumentException('non-nullable total_flashes cannot be null');
        }
        $this->container['total_flashes'] = $total_flashes;

        return $this;
    }

    /**
     * Gets total_smokes
     *
     * @return int|null
     */
    public function getTotalSmokes()
    {
        return $this->container['total_smokes'];
    }

    /**
     * Sets total_smokes
     *
     * @param int|null $total_smokes total_smokes
     *
     * @return self
     */
    public function setTotalSmokes($total_smokes)
    {
        if (is_null($total_smokes)) {
            throw new \InvalidArgumentException('non-nullable total_smokes cannot be null');
        }
        $this->container['total_smokes'] = $total_smokes;

        return $this;
    }

    /**
     * Gets total_he_grenades
     *
     * @return int|null
     */
    public function getTotalHeGrenades()
    {
        return $this->container['total_he_grenades'];
    }

    /**
     * Sets total_he_grenades
     *
     * @param int|null $total_he_grenades total_he_grenades
     *
     * @return self
     */
    public function setTotalHeGrenades($total_he_grenades)
    {
        if (is_null($total_he_grenades)) {
            throw new \InvalidArgumentException('non-nullable total_he_grenades cannot be null');
        }
        $this->container['total_he_grenades'] = $total_he_grenades;

        return $this;
    }

    /**
     * Gets total_molotovs
     *
     * @return int|null
     */
    public function getTotalMolotovs()
    {
        return $this->container['total_molotovs'];
    }

    /**
     * Sets total_molotovs
     *
     * @param int|null $total_molotovs total_molotovs
     *
     * @return self
     */
    public function setTotalMolotovs($total_molotovs)
    {
        if (is_null($total_molotovs)) {
            throw new \InvalidArgumentException('non-nullable total_molotovs cannot be null');
        }
        $this->container['total_molotovs'] = $total_molotovs;

        return $this;
    }

    /**
     * Gets total_enemies_flashed
     *
     * @return int|null
     */
    public function getTotalEnemiesFlashed()
    {
        return $this->container['total_enemies_flashed'];
    }

    /**
     * Sets total_enemies_flashed
     *
     * @param int|null $total_enemies_flashed total_enemies_flashed
     *
     * @return self
     */
    public function setTotalEnemiesFlashed($total_enemies_flashed)
    {
        if (is_null($total_enemies_flashed)) {
            throw new \InvalidArgumentException('non-nullable total_enemies_flashed cannot be null');
        }
        $this->container['total_enemies_flashed'] = $total_enemies_flashed;

        return $this;
    }

    /**
     * Gets avg_utility_score_value
     *
     * @return float|null
     */
    public function getAvgUtilityScoreValue()
    {
        return $this->container['avg_utility_score_value'];
    }

    /**
     * Sets avg_utility_score_value
     *
     * @param float|null $avg_utility_score_value avg_utility_score_value
     *
     * @return self
     */
    public function setAvgUtilityScoreValue($avg_utility_score_value)
    {
        if (is_null($avg_utility_score_value)) {
            throw new \InvalidArgumentException('non-nullable avg_utility_score_value cannot be null');
        }
        $this->container['avg_utility_score_value'] = $avg_utility_score_value;

        return $this;
    }

    /**
     * Gets avg_equipment_value
     *
     * @return float|null
     */
    public function getAvgEquipmentValue()
    {
        return $this->container['avg_equipment_value'];
    }

    /**
     * Sets avg_equipment_value
     *
     * @param float|null $avg_equipment_value avg_equipment_value
     *
     * @return self
     */
    public function setAvgEquipmentValue($avg_equipment_value)
    {
        if (is_null($avg_equipment_value)) {
            throw new \InvalidArgumentException('non-nullable avg_equipment_value cannot be null');
        }
        $this->container['avg_equipment_value'] = $avg_equipment_value;

        return $this;
    }

    /**
     * Gets rounds_as_t
     *
     * @return int|null
     */
    public function getRoundsAsT()
    {
        return $this->container['rounds_as_t'];
    }

    /**
     * Sets rounds_as_t
     *
     * @param int|null $rounds_as_t rounds_as_t
     *
     * @return self
     */
    public function setRoundsAsT($rounds_as_t)
    {
        if (is_null($rounds_as_t)) {
            throw new \InvalidArgumentException('non-nullable rounds_as_t cannot be null');
        }
        $this->container['rounds_as_t'] = $rounds_as_t;

        return $this;
    }

    /**
     * Gets rounds_as_ct
     *
     * @return int|null
     */
    public function getRoundsAsCt()
    {
        return $this->container['rounds_as_ct'];
    }

    /**
     * Sets rounds_as_ct
     *
     * @param int|null $rounds_as_ct rounds_as_ct
     *
     * @return self
     */
    public function setRoundsAsCt($rounds_as_ct)
    {
        if (is_null($rounds_as_ct)) {
            throw new \InvalidArgumentException('non-nullable rounds_as_ct cannot be null');
        }
        $this->container['rounds_as_ct'] = $rounds_as_ct;

        return $this;
    }

    /**
     * Gets t_side_win_rate
     *
     * @return float|null
     */
    public function getTSideWinRate()
    {
        return $this->container['t_side_win_rate'];
    }

    /**
     * Sets t_side_win_rate
     *
     * @param float|null $t_side_win_rate t_side_win_rate
     *
     * @return self
     */
    public function setTSideWinRate($t_side_win_rate)
    {
        if (is_null($t_side_win_rate)) {
            throw new \InvalidArgumentException('non-nullable t_side_win_rate cannot be null');
        }
        $this->container['t_side_win_rate'] = $t_side_win_rate;

        return $this;
    }

    /**
     * Gets ct_side_win_rate
     *
     * @return float|null
     */
    public function getCtSideWinRate()
    {
        return $this->container['ct_side_win_rate'];
    }

    /**
     * Sets ct_side_win_rate
     *
     * @param float|null $ct_side_win_rate ct_side_win_rate
     *
     * @return self
     */
    public function setCtSideWinRate($ct_side_win_rate)
    {
        if (is_null($ct_side_win_rate)) {
            throw new \InvalidArgumentException('non-nullable ct_side_win_rate cannot be null');
        }
        $this->container['ct_side_win_rate'] = $ct_side_win_rate;

        return $this;
    }

    /**
     * Gets t_side_kd
     *
     * @return float|null
     */
    public function getTSideKd()
    {
        return $this->container['t_side_kd'];
    }

    /**
     * Sets t_side_kd
     *
     * @param float|null $t_side_kd t_side_kd
     *
     * @return self
     */
    public function setTSideKd($t_side_kd)
    {
        if (is_null($t_side_kd)) {
            throw new \InvalidArgumentException('non-nullable t_side_kd cannot be null');
        }
        $this->container['t_side_kd'] = $t_side_kd;

        return $this;
    }

    /**
     * Gets ct_side_kd
     *
     * @return float|null
     */
    public function getCtSideKd()
    {
        return $this->container['ct_side_kd'];
    }

    /**
     * Sets ct_side_kd
     *
     * @param float|null $ct_side_kd ct_side_kd
     *
     * @return self
     */
    public function setCtSideKd($ct_side_kd)
    {
        if (is_null($ct_side_kd)) {
            throw new \InvalidArgumentException('non-nullable ct_side_kd cannot be null');
        }
        $this->container['ct_side_kd'] = $ct_side_kd;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


