<?php
/**
 * MatchTeamResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NoScope API
 *
 * Publicly available API for the NoScope platform. Requires authentication for all endpoints. Get your API key from the NoScope dashboard. API Rate Limiting applies to all endpoints and are currently capped at 100 requests per hour. Request api access at <a href='https://CSSkill.com/api'>https://CSSkill.com/api</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@CSSkill.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MatchTeamResponseTest Class Doc Comment
 *
 * @category    Class
 * @description MatchTeamResponse
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MatchTeamResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MatchTeamResponse"
     */
    public function testMatchTeamResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "team_name"
     */
    public function testPropertyTeamName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "players"
     */
    public function testPropertyPlayers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "score"
     */
    public function testPropertyScore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
