<?php
/**
 * UserStatsResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NoScope API
 *
 * Publicly available API for the NoScope platform. Requires authentication for all endpoints. Get your API key from the NoScope dashboard. API Rate Limiting applies to all endpoints and are currently capped at 100 requests per hour. Request api access at <a href='https://CSSkill.com/api'>https://CSSkill.com/api</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@CSSkill.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UserStatsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description UserStatsResponse
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UserStatsResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UserStatsResponse"
     */
    public function testUserStatsResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "matches_played"
     */
    public function testPropertyMatchesPlayed()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "wins"
     */
    public function testPropertyWins()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "losses"
     */
    public function testPropertyLosses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ties"
     */
    public function testPropertyTies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "win_rate"
     */
    public function testPropertyWinRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_kills"
     */
    public function testPropertyTotalKills()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_deaths"
     */
    public function testPropertyTotalDeaths()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_assists"
     */
    public function testPropertyTotalAssists()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_headshots"
     */
    public function testPropertyTotalHeadshots()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_damage"
     */
    public function testPropertyTotalDamage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_mvps"
     */
    public function testPropertyTotalMvps()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_kills_per_match"
     */
    public function testPropertyAvgKillsPerMatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_deaths_per_match"
     */
    public function testPropertyAvgDeathsPerMatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_assists_per_match"
     */
    public function testPropertyAvgAssistsPerMatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_headshots_per_match"
     */
    public function testPropertyAvgHeadshotsPerMatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_kills_per_round"
     */
    public function testPropertyAvgKillsPerRound()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_deaths_per_round"
     */
    public function testPropertyAvgDeathsPerRound()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "kd_ratio"
     */
    public function testPropertyKdRatio()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "kast_percentage"
     */
    public function testPropertyKastPercentage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "adr"
     */
    public function testPropertyAdr()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hs_percentage"
     */
    public function testPropertyHsPercentage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_hltv_rating"
     */
    public function testPropertyAvgHltvRating()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_hltv_rating_3"
     */
    public function testPropertyAvgHltvRating3()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_rating"
     */
    public function testPropertyAvgRating()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_personal_performance"
     */
    public function testPropertyAvgPersonalPerformance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rating_trend"
     */
    public function testPropertyRatingTrend()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_aim_score"
     */
    public function testPropertyAvgAimScore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_utility_score"
     */
    public function testPropertyAvgUtilityScore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_positioning_score"
     */
    public function testPropertyAvgPositioningScore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "clutch_attempts"
     */
    public function testPropertyClutchAttempts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "clutch_wins"
     */
    public function testPropertyClutchWins()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "clutch_win_rate"
     */
    public function testPropertyClutchWinRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "clutch_1v1_attempts"
     */
    public function testPropertyClutch1v1Attempts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "clutch_1v1_wins"
     */
    public function testPropertyClutch1v1Wins()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "clutch_1v2_wins"
     */
    public function testPropertyClutch1v2Wins()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "clutch_1v3_wins"
     */
    public function testPropertyClutch1v3Wins()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_2k_rounds"
     */
    public function testPropertyTotal2kRounds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_3k_rounds"
     */
    public function testPropertyTotal3kRounds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_4k_rounds"
     */
    public function testPropertyTotal4kRounds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_5k_rounds"
     */
    public function testPropertyTotal5kRounds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_aces"
     */
    public function testPropertyTotalAces()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "opening_kills"
     */
    public function testPropertyOpeningKills()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "opening_deaths"
     */
    public function testPropertyOpeningDeaths()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "opening_duel_success_rate"
     */
    public function testPropertyOpeningDuelSuccessRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trade_kills"
     */
    public function testPropertyTradeKills()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trade_opportunities"
     */
    public function testPropertyTradeOpportunities()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trade_success_rate"
     */
    public function testPropertyTradeSuccessRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_flashes"
     */
    public function testPropertyTotalFlashes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_smokes"
     */
    public function testPropertyTotalSmokes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_he_grenades"
     */
    public function testPropertyTotalHeGrenades()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_molotovs"
     */
    public function testPropertyTotalMolotovs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_enemies_flashed"
     */
    public function testPropertyTotalEnemiesFlashed()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_utility_score_value"
     */
    public function testPropertyAvgUtilityScoreValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "avg_equipment_value"
     */
    public function testPropertyAvgEquipmentValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rounds_as_t"
     */
    public function testPropertyRoundsAsT()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rounds_as_ct"
     */
    public function testPropertyRoundsAsCt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "t_side_win_rate"
     */
    public function testPropertyTSideWinRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ct_side_win_rate"
     */
    public function testPropertyCtSideWinRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "t_side_kd"
     */
    public function testPropertyTSideKd()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ct_side_kd"
     */
    public function testPropertyCtSideKd()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
